### ISSUE TITLE
When using POCOs as dictionary keys, how I access them inside the template?

### ISSUE THREAD

**Issue by deanebarker** [scriban/scriban#157]
What is the state of accessing dictionary entries that are indexed by objects?

```
var dict = new Dictionary<MyClass, MyOtherClass>();
dict.Add(instanceOfMyClass, instanceOfMyOtherClass);
```
In the template:
```
{{ dict[instance_of_my_class].any_property }}
```
This throws an error saying `dict[instance_of_my_class]` is `null`.

I can list `{{ dict }}` and I know it has all the entries in it. And re-accessing my entry through C# works fine. So I know the dictionary has the entry, and I use the object elsewhere in Scriban, so I know the `{{ instanceOfMyClass }}` object is the right key.

The Scriban capable of accessing dictionary entries keyed this way?  And is `instance_of_my_class` in the template the same as `instanceOfMyClass` in C#?  Will those keys match up?

**Comment by deanebarker** [comment]
FYI -- any attempt to run `{{ dict }}` through `object.keys` or `object.values` gives me:

```
'Unable to convert parameter #0 of type `System.Collections.Generic.Dictionary`2[BlogData.Post,BlogData.PostContext]` to type `System.Collections.Generic.IDictionary`2[System.String,System.Object]`'
```

**Comment by xoofx** [comment]
> What is the state of accessing dictionary entries that are indexed by objects?

Unfortunately, It's not supported. Dictionary keys are required to be strings (like json objects)

**Comment by deanebarker** [comment]
I had tried to make the keys strings, but still couldn't get it to work, and then I turned it to `<string,object>` and it worked. So:

```
dict.ToDictionary(i => i.Key, i=>(object)i.Value);
```

It wouldn't accept it if the value is `MyOtherClass`. It literally has to be cast down to an `object`.

Is this right?
