### ISSUE TITLE
Add special assignment operators

### ISSUE THREAD

**Issue by Aux** [scriban/scriban#158]
C# has a series of operators that can be used to shorten statements when performing actions on a variable. Documentation of which can be found [at this link](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators). It'd be nice to have this in scriban.

**Increment** `++`
Increment a value by 1
`var number = 1; number++;` 

**Decrement** `--`
Decrement a value by 1
`var number = 1; number--;`

**Addition** `+=`
Add `<left>` to `<right>` for numbers, or append `<right>` to `<left>` for strings.
`var number = 1; number += 1;`
`var text = "Hello"; text += " World";`

**Subtraction** `-=`
Subtract `<left>` from `<right>`.
`var number = 1; number -= 1;`

**Multiplication** `*=`
Get the product of `<left>` and `<right>`.
`var number = 2; number *= 2;`

**Division** `/=`
Get the quotient of `<left>` and `<right>`.
`var number = 2; number /= 2;`

**Comment by xoofx** [comment]
Personally no spare time left, but PR welcome
