### ISSUE TITLE
Print all fields/collections of a .NET object?

### ISSUE THREAD

**Issue by Mortana89** [scriban/scriban#161]
Hello,

Is there a way to print all the fields and collections that are accessible in the template, of a .NET object?
I read pprint somewhere but that was not recognized. 
It would make life much easier, so I can see what Scriban is making of my .net objects easily.

Thanks!

**Comment by xoofx** [comment]
Maybe this [kind of code](https://github.com/lunet-io/scriban/blob/master/src/Scriban.Tests/TestFiles/400-builtins/400-builtins.txt)?

**Comment by Mortana89** [comment]
Does this go multiple levels deep?
________________________________

**Comment by xoofx** [comment]
nope, you would need to use `object.typeof` detect if it is an object and call dump_members recursively, it would also require a depth int, increment/decrement it...etc.
