### ISSUE TITLE
Anonymous object - multiple levels deep?

### ISSUE THREAD

**Issue by Mortana89** [scriban/scriban#162]
Hello,

I'm trying to render a template with an anonymous object that is multiple levels deep.
For some reason, I'm getting errors that property X on Y does not exist.
What is the appropriate way of rendering a template with a dynamic/anonymous object that has multiple levels?

This is how I'm trying this:

```
public void MyFunction(object dataObject)
{
  var output = tpl.Render(new { dataObject });
}
```

dataObject is populated by asp.net core. I have a controller that is like:

```
public async Task<IActionResult> TestTemplate(string templateuuid, [FromBody] object requestBody)
        {
            GetTemplateOutputForDataObjectCommand cmd = new GetTemplateOutputForDataObjectCommand(templateuuid, requestBody);

            string result = await _mediator.Send(cmd);

            return Response(result, true);
        }
}
```

Thanks!

**Comment by xoofx** [comment]
it's difficult to say from your sample, but keep in mind that properies are being renamed by default (e.g "SomeProperty" becomes "some_property") See [MemberRenamer doc](https://github.com/lunet-io/scriban/blob/master/doc/runtime.md#member-renamer) for more details
