### ISSUE TITLE
Announcement: ScribanExpress 

### ISSUE THREAD

**Issue by timker** [scriban/scriban#170]
I've created [ScribanExpress](https://github.com/sevenwestmedia-labs/ScribanExpress).
This has given us significant performance boost (more below).

It Uses Scriban to Generate an AST then converts those to expressions. I've generally tried to keep to the Scriban behaviour, most differences are due to features not being implemented... yet. I'm keen to get feedback, to help prioritise new features. Any opinions are welcome. 

Preview releases, are up on nuget. We are using this in production.
[ScribanExpress Nuget](https://www.nuget.org/packages?q=ScribanExpress)
There is a Demo, and benchmarks in the repo.

We get huge performance improvements.
For the products example we see about an 8 times improvement
```  
|             Method |       Mean |     Error |    StdDev | Ratio |
|------------------- |-----------:|----------:|----------:|------:|
| ExpressProducts500 |   163.2 us | 0.8232 us | 0.6874 us |  0.13 |
| ScribanProducts500 | 1,273.9 us | 3.0741 us | 2.7251 us |  1.00 |
```

For our use cases, lots of little simple templates
We are seeing up to 350x perf improvement in these cases
```
|             Method |         Mean |      Error |    StdDev | Ratio |
|------------------- |-------------:|-----------:|----------:|------:|
| 'Express Hello 50' |     9.684 us |  0.0548 us | 0.0512 us | 0.004 |
| 'Scriban Hello 50' | 2,752.831 us | 10.6530 us | 9.9648 us | 1.000 |
```
 
Notable points
* The first render of a template will invoke an expression compile, this will be slow.... then super fast.
* ScribanExpress *currently* caches on template string, so probably not suited for huge templates right now.
* One feature is the ability to call methods on any object, this is a slight departure from Scriban.
* Security (especially around calling methods) has not been applied, i.e you can call `anyobject.GetType`

**Comment by endeffects** [comment]
@xoofx  Do you plan to adapt some of these optimizations?

**Comment by xoofx** [comment]
> @xoofx Do you plan to adapt some of these optimizations?

Personally no. AOT is a different approach that I evaluated when designing Scriban, but I would have had to duplicate a significant chunk of the runtime to make it 100% compatible. It would be quite some work, and beyond PR mgt and small bug fixes, I don't plan to work on any substantial work on Scriban.
