### ISSUE TITLE
Update documentation for regex.replace to use verbatim strings

### ISSUE THREAD

**Issue by bradlis7** [scriban/scriban#176]
I'm writing a regular expression replacement, and when I try to match whitespace `\s`, it says it's an invalid character. `\w` is also invalid. 

    Unexpected escape character `s` in string. Only 0 ' \ " b f n r t v u0000-uFFFF x00-xFF are allowed

Can we expand allowed characters for Regular Expressions?

https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions

**Comment by xoofx** [comment]
That's because you are using a regular string (exactly like in C#)
You need to use [verbatim strings](https://github.com/lunet-io/scriban/blob/master/doc/language.md#31-strings) with backsticks

**Comment by bradlis7** [comment]
Ah, much better, @xoofx . I'll change this request to update the documentation for `regex.replace` to use that syntax?
