### ISSUE TITLE
The function `date.to_string` was not found

### ISSUE THREAD

**Issue by PhilippCh** [scriban/scriban#190]
Working with Unity 2018.2, it seems like the pipe `date.to_string` cannot be found when rendering via

```
var template = Template.Parse(data.Template);
template.Render(data.Model);
```

Template looks like this:

```
It's an old newspaper from {{Date | date.to_string `%d %b %Y`}}.
```

Any help would be greatly appreciated!

**Comment by hahn-kev** [comment]
I've just tested it and it seems to work fine. Can you share the error message and the type Model is using? it could be that it's not finding Date and so that's giving you an error.

**Comment by pluveto** [comment]
I encountered the same error, and finally I found that it is because the first argument is missing.
```c#
<time class="post-date" datetime="{{ page.date | date.to_string '%Y-%m-%d' }}">{{ page.date | date_to_string }}</time>
```
In my case, date.to_string does exist. The reason why I got `The function date.to_string was not found.` is that I forgot to set value for `page.date`. Hope this helps.
