### ISSUE TITLE
Question about using external assemblies

### ISSUE THREAD

**Issue by mikeprag** [scriban/scriban#207]
Hi,
I came across Scriban as I am trying to find an alternative to T4 template. I really like Scriban but I'm not sure if it's possible to use an external assembly in the way I want. Basically, we have an Excel sheet that holds a lot of configuration information and we use Syncfusion XLS.IO to read the excel sheet. I need to do something like this in the script

```
ExcelEngine excelEngine = new ExcelEngine();
IApplication application = excelEngine.Excel;
application.Workbooks.OpenReadOnly(pathToContentGuide);

/****** Read in our parameters first *****/
IWorkbook workbook = application.Workbooks[0];
IWorksheet sheetExternalLookups = workbook.Worksheets["ExternalLookups"];
 foreach (var row in sheetExternalLookups.Rows)
{
WriteLine (Stuff from the excel sheet)
}
```
Can I achieve this at all or do I need to pass in all the instantiated worksheets (I actually have about 8 worksheets)

Any help gratefully received

Thanks

Mike

**Comment by xoofx** [comment]
Have you tried? As long as the objects you are accessing have plain properties, it should work. Scriban is good for constraint models, but is not a good fit if you are requiring to access methods for example (which could happen on some .NET models like Excel API)
