### ISSUE TITLE
Allow retrieving the list of expected variables for a template

### ISSUE THREAD

**Issue by SeanFarrow** [scriban/scriban#223]
Hi,

Is it possible to retrieve the list of variables a template expects to be filled in?
I'm currently looking at templating engines and this is a requirement we have.

Thanks,
Sean.

**Comment by xoofx** [comment]
It is possible but not straightforward, due to the lack of a built-in AST syntax visitor. 
There is a PR #187 but the design/implementation has to be a bit reconsidered. It is not much work, but I personally don't have time to work on this these days.

**Comment by SeanFarrow** [comment]
Should I use the existing PR or write a new one?
Is this project still active, if not is there something else I could use?
Thanks,
Sean.

**Comment by xoofx** [comment]
> Should I use the existing PR or write a new one?

You can reuse parts of the PR if you want. Then you can follow how it is usually done from [Tomlyn project](https://github.com/xoofx/Tomlyn/blob/7fd3bf419bf15fbbb80159004e4b4449bab99621/src/Tomlyn/Syntax/SyntaxNode.cs#L36-L59):

- `GetChildren()` on `ScriptNode`
- Implement the `GetChildrenImpl()` for each derived class of `ScriptNode`. The implementation would follow what is done in the Visitor of the original PR.
- Create a simple visitor like this [one](https://github.com/xoofx/Tomlyn/blob/7fd3bf419bf15fbbb80159004e4b4449bab99621/src/Tomlyn/Syntax/SyntaxVisitor.cs)

> Is this project still active, if not is there something else I could use?

If you are asking if the project is used, yes, I have heard it is used in commercial products.
Is it active? I try to respond to issues/questions but as this project is no longer a priority in my sparetime, it can be active only if people are willing to contribute back to it, help to fix issues... 😉

**Comment by SeanFarrow** [comment]
Brilliant, I’ll work on this over the next few days.
Happy to help where I can.
Thanks,
Sean.
