### ISSUE TITLE
Template.Parse NullReferenceException when using triple curly bracket in certain scenario '2.1.3'

### ISSUE THREAD

**Issue by Jeroenh13** [scriban/scriban#240]
This throws a nullpointer

```
{{{~ for $e in Entity.Properties
    $e.Id
end ~}}
```

But when I change stuff around I get normal errors.
```
{{{~ for $e in Entity.Properties ~}}
    {{~ $e.Id ~}}
{{~ end ~}}
```

> Unexpected token `Invalid` while parsing object initializer. Expecting a simple identifier for the member name instead of `~`
> Error while parsing expression statement: Invalid token found `~`. Expecting <EOL>/end of line after: <expression>

And

```
{{{~
for $e in Entity.Properties
    $e.Id
end 
~}}
```

> Unexpected token `Invalid` while parsing object initializer. Expecting a simple identifier for the member name instead of `~`

**Comment by xoofx** [comment]
Indeed, the lexer is not well protected for malformed code enter/exit sequence.

**Comment by NeilMacMullen** [comment]
I can't reproduce this with the example code.  Is it still an issue?

**Comment by xoofx** [comment]
Fixed recently.
