### ISSUE TITLE
Comparing integers from JSON data

### ISSUE THREAD

**Issue by limeschool** [scriban/scriban#246]
Hello! I'm trying to compare two integers which I'm bringing in as JSON, i.e.:
```
var template = Template.ParseLiquid("{% if paginator.page != paginator.total_pages %}");
return template.Render(new { paginator = SomeJObject });
```

However, this yields the following error:
```<input>(47,24) : error : Unsupported types `1/Newtonsoft.Json.Linq.JValue` >= `3/Newtonsoft.Json.Linq.JValue` for binary operation```

I first thought that this is due to the two integers being `JValue`s, not technically `int`s, but if I replace one of them in the comparison with a hardcoded integer, it works, and the error does show their respective values (`1` and `3`, respectively), so I know Scriban knows what they are. I'd appreciate some guidance on this. Thank you.

**Comment by limeschool** [comment]
What's more strange is how the `==` comparison works, but `!=` doesn't. Operators such as `>=`, `<=`, `>`, and `<` fail as well. If the values cannot be compared as integers, how come `==` works but `!=` does not? This is puzzling me.

**Comment by xoofx** [comment]
The problem is that Scriban won't be able to compare external abitrary values. It's working if one of the argument is int because it will try to coerce the other argument to an int (and so the json value will work correctly).

I don't advice to use JSON object directly but to convert JSON objects to scriban objects instead before using them within scriban ( so ScriptObject, ScriptArray and proper values). It's much easier to work with. It's usually easy to do that with whatever JSON library you are using (For example parsing a [YAML stream to Scriban objects is relatively simple](https://github.com/lunet-io/lunet/blob/e89c8cbfe5205996737fe38d591b4bec61eefca5/src/Lunet.Yaml/YamlUtil.cs#L137-L187))

I couldn't add this as part of Scriban, as it is dependent on some JSON parsing, but it's usually straightforward to do it.

**Comment by xoofx** [comment]
Otherwise, for the problem with between `==` works but `!=`  this could be separate bug.

**Comment by xoofx** [comment]
Example of some code using System.Text.Json to convert to Scriban:

```c#
      private static object ConvertFromJson(JsonElement element)
        {
            switch (element.ValueKind)
            {
                case JsonValueKind.Object:
                    var obj = new ScriptObject();
                    foreach (var prop in element.EnumerateObject())
                    {
                        obj[prop.Name] = ConvertFromJson(prop.Value);
                    }

                    return obj;
                case JsonValueKind.Array:
                    var array = new ScriptArray();
                    foreach (var nestedElement in element.EnumerateArray())
                    {
                        array.Add(ConvertFromJson(nestedElement));
                    }
                    return array;
                case JsonValueKind.String:
                    return element.GetString();
                case JsonValueKind.Number:
                    if (element.TryGetInt32(out var intValue))
                    {
                        return intValue;
                    }
                    else if (element.TryGetInt64(out var longValue))
                    {
                        return longValue;
                    }
                    else if (element.TryGetUInt32(out var uintValue))
                    {
                        return uintValue;
                    }
                    else if (element.TryGetUInt64(out var ulongValue))
                    {
                        return ulongValue;
                    }
                    else if (element.TryGetDecimal(out var decimalValue))
                    {
                        return decimalValue;
                    }
                    else if (element.TryGetDouble(out var doubleValue))
                    {
                        return doubleValue;
                    }
                    else
                    {
                        throw new InvalidOperationException($"Unable to convert number {element}");
                    }
                case JsonValueKind.True:
                    return (KalkBool)true;
                case JsonValueKind.False:
                    return (KalkBool)false;
                default:
                    return null;
            }
        }
```

**Comment by limeschool** [comment]
Thanks for your very quick response! I'm using Newtonsoft Json.NET (as I'm on .NET Core), so I'll try to see if I can still pull this off. Your answer is quite detailed, thank you for the code sample!

**Comment by limeschool** [comment]
For anyone else using Json.NET in the future, this is what I ended up with:
```csharp
private static object ConvertFromJson(JObject element)
        {
            switch (element.Type)
            {
                case JTokenType.Object:
                    var obj = new ScriptObject();
                    foreach (var prop in element.Properties())
                    {
                        //Console.WriteLine(prop.Name + ": " + prop.Value.ToString());
                        obj[prop.Name] = prop.Value.ToObject<object>();
                    }

                    return obj;
                case JTokenType.Array:
                    var array = new ScriptArray();
                    foreach (var nestedElement in element.Descendants())
                    {
                        array.Add(ConvertFromJson(JObject.Parse(nestedElement.ToString())));
                    }
                    return array;
                case JTokenType.String:
                    return element.ToString();
                case JTokenType.Integer:
                    return element.ToObject<int>();
                case JTokenType.Float:
                    return element.ToObject<double>();
                case JTokenType.Boolean:
                    return element.ToObject<bool>();
                default:
                    return null;
            }
        }
```

However, this does not explain the fact that `==` worked earlier. It does fix my problem, though. Yay.
