### ISSUE TITLE
How to use objects inside Functions

### ISSUE THREAD

**Issue by kostyrin** [scriban/scriban#252]
If need to use some object inside Functions then it doesn't render value of the object. 
e.g. there is Translate function:
```cs
public static class TranslateFunctions
{
	private static Dictionary<string, string> translateMap = new Dictionary<string, string>
	{
		{ "body", "now: {{now_date | date.to_string '%Y' }}" }
	};
	public static string Translate(TemplateContext context, string key)
	{
		return translateMap[key];
	}
}
```

need to translate a body: 'now: {{now_date | date.to_string '%Y' }}'
then e.g. some unit test:
```cs
[Test]
public void TestFunctionWithTemplateContextAndTranslate()
{
	var parsedTemplate = Template.ParseLiquid("{{ 'body' | translate }}");
	Assert.False(parsedTemplate.HasErrors);

	var scriptObject = new ScriptObject();
	scriptObject.Import(typeof(TranslateFunctions));
	var context = new TemplateContext();
	context.PushGlobal(scriptObject);

        var scriptObjectForModel = new ScriptObject();
        scriptObjectForModel.Import(new { NowDate = DateTime.Now });
        context.PushGlobal(scriptObjectForModel);
	
	var result = parsedTemplate.Render(context);
	TextAssert.AreEqual("now: 2020", result);
}
```
in the result return 'now: {{now_date | date.to_string '%Y' }}' instead of 'now: 2020'
could you help which will be one solution?
thanks.

**Comment by xoofx** [comment]
You need to pass `TemplateContext` as a first parameter of your Translate function. Then you need to parse/evaluate dynamically the value of the translateMap. You can have a look at `object.eval` [commit](https://github.com/lunet-io/scriban/pull/230/commits/751cbe72f155e4fd3c434e5ce897af2fe1926eb7) where I have added support for dynamic evaluation.
Note that in your case, you don't want to evaluate a template but directly the expression, which requires a different parsing mode (see the documentation)
