### ISSUE TITLE
Consider auto-indenting when invoking functions

### ISSUE THREAD

**Issue by kzu** [scriban/scriban#253]
Consider the scenario where you're rendering a hierarchical structure. In this case, a typical looping structure isn't suitable, and you'd instead declare a function that keeps calling itself recursively as it walks down the tree. 

Say you have a structure like the following as the model for the rendering:

```csharp
class Model
{
    public Area RootArea { get; set; }
}

class Area 
{
    public string Name { get; set; }
    public Dictionary<string, string> Values { get; set; }
    public List<Area> NestedAreas { get; set; }
}
```

A template to render that as nested C# classes declaring constants for each Key/Value would look like the following:

```
{{ func render }}
    public static class {{ $0.Name }}
    {
        {{~ for pair in $0.Values ~}}
	    public static string {{ pair .Key }} => @"{{ pair .Value }}";
        {{~ end ~}}

        {{ for area in $0.NestedAreas 
            render area
           end }}
    }
{{ end }}

using System;
using System.Globalization;

partial class Constants
{
    {{ render RootArea }}
}
```

This would render the recursive structure properly, but the indenting will be all "wrong". The function defines one nesting level only, and each recursive call will have the same nesting level. When rendering recursive structures, it would seem more natural for the nesting of the previous level to be taken into account, so the resulting text is indented "properly" on each subsequent call to the function.

The T4 templating engine from Microsoft, for example, provides explicit PushIndent/PopIndent methods you can call to explicitly call such indenting. Given the strong focus that Scriban has on provinding intuitive whitespace handling options, a similar solution might not be the optimal or more idiomatic mechanism. Maybe some way of tagging the function itself to denote "indent-ness" might be better?

Is there already something built-in I have missed? I searched the (nicely extensive language docs!) but couldn't find anything obvious supported built-in.

I realize this might be a tough one to solve in a backwards compatible way, since the function effectively behaves as if it had `~` in its declaration: 

```
{{~ func render ~}}
```
(since it does not consider the whitespace at the call-site and renders its own content regardless of it).

The more intuitive behavior (which might not be such breaking change, unless you're calling functions recursively) would be to note the current indentation level when a function is invoked, and unless `{{~` is specified in the function, append that whitespace before every subsequent line rendered by the function.

Thanks for a fantastic template engine! 💯

**Comment by xoofx** [comment]
I agree, it would be nice, but my previous attempt at indenting haven't been so far super successful, mostly because while I would like to have this feature as well, I'm not motivated enough to spend time trying to solve this.
So if you have the courage, PR welcome! 😉

**Comment by mikechristiansenvae** [comment]
@xoofx - I've been thinking about this.  

There's really two parts of @kzu 's request.

1. Have some way of explicitly indenting/dedenting the output (like T4's `PushIndent` and `PopIndent` methods)
2. Automatically indenting/dedenting based on function scope.

The second one is the much harder piece.  

----

But, I'm reasonably sure the first part (explicit indent/dedent) is feasible.

My suggested approach is to add some built-in functions (maybe they are only added if an option is passed to `TemplateContext`'s constructor?)

- `indent.start(string tabString)` - Calls `TemplateContext.PushOutput`, with a `TextWriterOutput`, which wraps [System.CodeDom.Compiler.IndentedTextWriter](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.indentedtextwriter?view=netstandard-2.0) (which is a `TextWriter`). The `string` argument is optional, and represents the `tabString` parameter of `IndentedTextWriter`'s constructor.
- `indent.indent(int? level = null)` - If the `int` arg is provided, sets the value of `IndentedTextWriter.Indent`.  If it is not provided, increments `IndentedTextWriter.Indent`
- `indent.dedent()` - decrements `IndentedTextWriter.Indent`
- `indent.tab_string` - Gets the tab string (read-only!)
- `indent.stop` - Calls `TemplateContext.PopOutput`

Now, I'm not sure the specifics of how `PushOutput` and `PopOutput` work, so I'm not sure how reasonable this is.

But, at the very least, @kzu could implement their scenario by manually indenting prior to calling their `render` function, and manually dedenting after returning from the method.

**Comment by xoofx** [comment]
Late to respond to this, but this was fixed recently https://github.com/scriban/scriban/issues/398#issuecomment-1030839862, [auto-indentation](https://github.com/scriban/scriban/blob/b6e558819d46146e052b297b1a2715201a32bc2e/doc/language.md#15-auto-indentation) is the default behavior.

**Comment by xoofx** [comment]
> I request reopening this issue @xoofx. I've tested the provided code under 5.4.1, 5.4.2, and 5.10.0 and none of them output (what I believe to be) the expected code.

Please create a new issue.
