### ISSUE TITLE
Authenticode signing NuGet package

### ISSUE THREAD

**Issue by chriswbarrett** [scriban/scriban#255]
This is an amazing project! We're looking to use it internally at Microsoft and wondering whether you're willing to [Authenticode sign](https://comodosslstore.com/resources/how-to-sign-code-microsoft-authenticode/#:~:text=8%20Quick%20Steps%20on%20How%20to%20Sign%20Code.,you%E2%80%99re%20timestamping%20and%20then%20click%20next%20again.%20
) your the DLLs in Scriban.Signed NuGet package

**Comment by xoofx** [comment]
Hm, personally I would not pay for that from my pocket... but I think that dotnet foundation might be able to provide that.

I can see how much work it would be to require to move Scriban to the .NET foundation if you want?
