### ISSUE TITLE
Different behaviors between static method import VS delegate import when dealing with params

### ISSUE THREAD

**Issue by mk0a1a** [scriban/scriban#260]
**Affect version: 2.1.4**

Hello, I found that importing functions through a static method in classes versus importing via delegates have different behaviors when `params` are set as parameters.

For example:

```csharp
class Program
{
    private class Test
    {
        public static string Execute(params object[] args)
        {
            var str = "";

            foreach (var arg in args)
            {
                var s = (string) arg;
                str += s + " ";
            }

            return str;
        }
    }

    private void Main()
    {
        var scriptObject = new ScriptObject();
        var context = new TemplateContext();
        context.PushGlobal(scriptObject);

        scriptObject.Import(typeof(Test));

        var template = Template.Parse("Hello, {{ execute \"john\" \"doe\" }}!");
        Console.WriteLine(template.Render(context));
    }
}
```

Outputs `Hello, john doe !`, which is expected behavior. But when doing the same thing with delegates, it throws an error:

```csharp
class Program
{
    private delegate string Execute(params object[] args);

    private void Main()
    {
        Execute ex = (args) =>
        {
            var str = "";

            foreach (var arg in args)
            {
                var s = (string) arg;
                str += s + " ";
            }

            return str;
        };

        var scriptObject = new ScriptObject();
        var context = new TemplateContext();
        context.PushGlobal(scriptObject);

        scriptObject.Import("execute", ex);

        var template = Template.Parse("Hello, {{ execute \"john\" \"doe\" }}!");
        Console.WriteLine(template.Render(context));
    }
}
```

Error:

```
Unhandled exception. <input>(1,11) : error : Unable to convert parameter #0 of type `System.String` to type `System.Object[]`
```

Note that both method signatures are exactly the same. As for my use case, I actually need to use delegates as I am trying to import a method from a 3rd party library. Is this by design or is it a bug? What is the recommended way to import just one method from an object instance, for example, like the `Add` method from `List`?

**Comment by xoofx** [comment]
So I don't recall the details, but the code is relying on the underlying method bound because for example with `Action`/`Func` they can't express `params` and they are usually easier to work with.

Usually to import methods, I'm simply using something like `scriptObject.Import("execute", (Action<object>)Add);`
