### ISSUE TITLE
Feature: Enum get DisplayAttribute

### ISSUE THREAD

**Issue by totpero** [scriban/scriban#276]
Hi, 

For the enum type will be nice if you cen get the displayAttrinute if exist
If you add something like this in [this](https://github.com/lunet-io/scriban/blob/d9458f5655a9c6bb374e6a67620039d7f99b30c9/src/Scriban/TemplateContext.Helpers.cs#L105) function:

```
if (value is Enum e)
{
    var enumType = e.GetType();

    return enumType
        .GetMember(e.ToString())
        .First(x => x.MemberType == MemberTypes.Field && ((FieldInfo)x).FieldType == enumType)
        .GetCustomAttribute<DisplayAttribute>()?.Name ?? e.ToString();
}
```

**Comment by totpero** [comment]
And [here ](https://github.com/lunet-io/scriban/blob/d9458f5655a9c6bb374e6a67620039d7f99b30c9/src/Scriban/Helpers/ReflectionHelper.cs#L56)also need to be added this:
` if (type == typeof(Enum)) return "enum";`

**Comment by xoofx** [comment]
> For the enum type will be nice if you cen get the displayAttrinute if exist
> If you add something like this in this function:

You can override `ObjectToString` to provide this.

> And here also need to be added this:
> if (type == typeof(Enum)) return "enum";

Yep, can you send a PR?

**Comment by totpero** [comment]
@xoofx 

> You can override ObjectToString to provide this.
 can you show me one example how to override ObjectToString because in ObjectToString is wrote some logic I don't have access to all code path.

> Yep, can you send a PR?
I have created PR.

Thanks 👍

**Comment by totpero** [comment]
I solve this using:

```
public override string ObjectToString(object value, bool nested = false)
        {
            return value switch
            {
                //custom bool value
                bool b => b ? BoolFunctions.DefaultTrue : BoolFunctions.DefaultFalse,
                //custom for enum type
                Enum e => EnumFunctions.Display(e),
                _ => base.ObjectToString(value, nested)
            };
        }
```

Enum Function:

```
public class EnumFunctions: ScriptObject
    {
        /// <summary>
        /// Get Display Atrribute value
        /// </summary>
        /// <param name="enum">The input enum</param>
        /// <returns>The <see cref="System.ComponentModel.DataAnnotations.DisplayAttribute"/> Name</returns>
        public static string Display(Enum @enum)
        {
            var enumType = @enum.GetType();

            return enumType
                .GetMember(@enum.ToString())
                .First(x => x.MemberType == MemberTypes.Field && ((FieldInfo)x).FieldType == enumType)
                .GetCustomAttribute<DisplayAttribute>()?.Name ?? @enum.ToString();
        }
    }
```
