### ISSUE TITLE
Abstract Syntax Tree : span of a parent node is smaller than the sum of spans of its children

### ISSUE THREAD

**Issue by NeVeSpl** [scriban/scriban#279]
For the given template:
```{{filePath = "result\\" | string.Append class.Name }}```
we get following syntax tree:
![image](https://user-images.githubusercontent.com/11632757/102719548-0a28e000-42ef-11eb-85eb-c24453b8b3df.png)

where in brackets are printed out offsets of span :  ({node.Span.Start.Offset} - {node.Span.End.Offset}):

It is a bug, or by design?

**Comment by xoofx** [comment]
It is likely a bug, but I don't have personal time to investigate this issue, feel free to investigate it.
