### ISSUE TITLE
Round _up_ math.divided_by?

### ISSUE THREAD

**Issue by DJF3** [scriban/scriban#282]
Team,

Is it possible to do a math.divided_by and round **UP** the result?

Now:
`{{ 25 | math.divided_by 2 }}  = 12.5 so it will return 12`

**The goal** is to "round up" the 12.5 to 13 instead of down to 12. 

**IF you could check if the start number _is_odd_ or _is_even_**, then you could
- **if_odd**: add 1 to 25 --> 26 --> /2 = 13
- **if_even**: --> /2

**Comment by xoofx** [comment]
You can probably use something like `{{ (25 / 2) + 0.5 | math.round  }}`

**Comment by DJF3** [comment]
> You can probably use something like `{{ (25 / 2) + 0.5 | math.round }}`

_Smart_! But there's a problem. When the number is "24" (_even_) the result will be 24/2 = 12 + 0.5 = 12.5 | math.round = 13

- if ODD: add 1 to make it even and then divide by 2
- if EVEN: divide by 2

**Comment by xoofx** [comment]
Have you checked, it should give you 12, not 13?

**Comment by DJF3** [comment]
So strange..
```
     {{ abc = 34 }}
     _{{ (abc / 2) | math.round }}<BR>
     _{{ (abc / 2) | math.round 2 }}<BR>
     _{{ ((abc / 2) + 0.5) }}<br>
     _{{ ((abc / 2) + 0.5) | math.round }}><br>
     _{{ (34 / 2) + 0.5 | math.round }}
```
Result:
```
_17
_17
_17.5
_18 
_18
```

In the mean time I have found a "solution" by using an IF..THEN..ELSE statement, but it's not ideal :-)

`{{if (abc/2 | math.round 2) - (abc/2 | math.round) > 0 }}`
abc = 34  ----> if (17 - 17.5) > 0    (no)
abc = 35  ----> if (17.5 - 17) > 0     (yes)

...now my brain hurts...

**Comment by xoofx** [comment]
hm, in some cases, number will not round correctly with floating point numbers. You can try to use a custom function that wraps [double.Round(Double, MidpointRounding)](https://docs.microsoft.com/en-us/dotnet/api/system.math.round?view=net-5.0#System_Math_Round_System_Double_System_MidpointRounding_) using `MidpointRounding.AwayFromZero`

I can add maybe later a function `math.round_away_from_zero` but it won't solve all issues as explained in the doc linked.
