### ISSUE TITLE
Parametric function example from doc does not parse

### ISSUE THREAD

**Issue by deanebarker** [scriban/scriban#283]
I just want to point out that the example from the doc under "7.3 Parametric Functions" does not parse.

https://github.com/scriban/scriban/blob/master/doc/language.md#73-parametric-functions

```
var templateString = @"
{{func sub(x,y)
   ret x - y
end}}
	
{{sub 5 1}}
{{5 | sub 1}}
";

var template = Template.Parse(templateString);
```

This throws a couple errors:

```
Error while parsing function statement: Invalid token found `(`. Expecting <EOL>/end of line after: func <variable> ... end
```

and

```
Error while parsing function statement: The <end> statement was not found in: func <variable> ... end
```

**Comment by xoofx** [comment]
Which version of Scriban are you using?

**Comment by deanebarker** [comment]
Ah, sorry. An old one, it turns out. 

Updating fixed it.
