### ISSUE TITLE
Using nuget source package with enabled nullables creates warnings

### ISSUE THREAD

**Issue by badcel** [scriban/scriban#285]
In general the new nuget source package works fine. Thank you for your work. Now it is very easy to depend on Scriban in a source generator.

One small hickup is if you use the package in a project which enables the non nullable reference types feature there are ~600 warnings regarding nullables.

Now it is quite hard for me to differentiate between my own nullable warnings and the ones from Scriban.

**Comment by xoofx** [comment]
Yeah, Scriban is not nullable friendly. I don't have a plan to make it friendly, so ever PR welcome to disable the warning in each files or to implement the nullable entirely in Scriban. PR welcome.

**Comment by badcel** [comment]
I could disable the nullable feature per file. Where do you want to have the `#nullable disable` directive? Between copyright and using e.g.:

```C#
// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.

#nullable disable

using System;
using System.Collections;
```

**Comment by xoofx** [comment]
Yep, sounds good
