### ISSUE TITLE
Section, RenderSection in scriban

### ISSUE THREAD

**Issue by okursoft** [scriban/scriban#289]
Hello,

I'm trying to make Section and RenderSection feature with scriban like Razor Engine, but I couldn't succeed. How can I achieve this with scriban? Can you help?

I coded Script Custom Function called RenderPage. First of all, Layout is parsing. If there is a situation that contains {{renderpage}}, it pulls the Page html here. I want to add some data inside the <head> </head> tag in Layout in the Page html. But I couldn't do that.

Thank you

**Comment by okursoft** [comment]
Hi @xoofx,

Is there a mistake in the question I asked? Can such a thing be done? can you help me ?

**Comment by xoofx** [comment]
I can't tell exactly, but if `RenderSection(name)` and you want to execute `name`, it could be either an include that you load or a function that you call directly. In case of a function:

```
{{ 
func test; ret "yo"; end;

func RenderSection; this[$0]; end;

RenderSection "test"
}}
```

It will print "yo"

There is plenty of ways to implement it, but it's really up to your requirements.
