### ISSUE TITLE
How do I override ScriptForStatement.LoopItem

### ISSUE THREAD

**Issue by ste-bel** [scriban/scriban#290]
I want to sub-class ScriptForStatement.LoopItem to add code to handle my framework polymorphic table records extensions :

{{~ for ResultsRow in Results ~}}
- Results is a regular list
- Each ResultsRow is a polymorphic row (it is in fact a collection of rows of different nature).

For each ResultsRow set by LoopItem, I want to add some code to add other ResultsRowAsXxxx extracted from ResultsRow

protected override object LoopItem(TemplateContext context, ScriptLoopStatementBase.LoopState state);

How do I hookup a new subclass of ScriptForStatement?

**Comment by xoofx** [comment]
A subclass for `ScriptForStatement` is probably not the right approach (it's build at parsing time) as extensions are usually made in Scriban through `TemplateContext`, so I would suggest more to look from there.

One potential way to extend it would be to make the method `TemplateContext.SetLoopVariable` virtual and to override it, as it is used by the for/while loop to setup the item variable of the loop:

https://github.com/scriban/scriban/blob/e33c78b53f3830214ba7ebc9505c9e92b3a26617/src/Scriban/TemplateContext.Variables.cs#L149

So probably just adding  `virtual` to this method would be enough in your case? PR welcome.

**Comment by ste-bel** [comment]
> A subclass for `ScriptForStatement` is probably not the right approach (it's build at parsing time) as extensions are usually made in Scriban through `TemplateContext`, so I would suggest more to look from there.
> 
> One potential way to extend it would be to make the method `TemplateContext.SetLoopVariable` virtual and to override it, as it is used by the for/while loop to setup the item variable of the loop:
> 
> https://github.com/scriban/scriban/blob/e33c78b53f3830214ba7ebc9505c9e92b3a26617/src/Scriban/TemplateContext.Variables.cs#L149
> 
> So probably just adding `virtual` to this method would be enough in your case? PR welcome.

I'd like to help, I'm using scriban a lot and loving it but I've never done a pull request.  Should I checkout the code first, then change it and then push/commit?

**Comment by xoofx** [comment]
I made the change in the commit 927ecf2237420ae72a3cf4f258afd52767d76b14 - I was fixing an issue close to this method. This should be available in 3.3.0

**Comment by xoofx** [comment]
> I'd like to help, I'm using scriban a lot and loving it but I've never done a pull request. Should I checkout the code first, then change it and then push/commit?

Yeah, it's a normal workflow on GitHub, you should really learn it 😉  , it's easy if you are familiar with git. See [Creating an issue or pull request](https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/creating-an-issue-or-pull-request)
