### ISSUE TITLE
After updating to Scriban 3.2.2, templates are no longer working

### ISSUE THREAD

**Issue by gep13** [scriban/scriban#291]
This issue was raised as a result of a [Twitter conversation](https://twitter.com/xoofx/status/1343969863635771393).

We have a Scriban template, made up of the following files:

**index.sbn**
```
{{-
    include 'release-info'
    if milestone.target.description
        include 'milestone'
    end
    include 'issues' | string.rstrip
    if template_kind == "CREATE"
        include 'create/footer'
    end
~}}

```

**release_info**
```
{{
    if issues.count > 0
        if commits.count > 0
}}As part of this release we had [{{ commits.count }} {{ commits.count | string.pluralize "commit" "commits" }}]({{ commits.html_url }}) which resulted in [{{ issues.count }} {{ issues.count | string.pluralize "issue" "issues" }}]({{ milestone.target.html_url }}?closed=1) being closed.
{{      else
}}As part of this release we had [{{ issues.count }} {{ issues.count | string.pluralize "issue" "issues" }}]({{ milestone.target.html_url }}?closed=1) closed.
{{      end
    else if commits.count > 0
}}As part of this release we had [{{ commits.count }} {{ commits.count | string.pluralize "commit" "commits" }}]({{ commits.html_url }}).
{{  end -}}

```

**milestone.sbn**
```

{{ milestone.target.description }}

```

**issues**
```

{{ for issue_label in issue_labels
    include 'issue-details'
end }}

```

**issue-details**
```
__{{ issue_label }}__

{{ for issue in issues.items["issue_label"]
    include 'issue-note'
end }}

```

**issue-note**
```
- [__#{{ issue.number }}__]({{ issue.html_url }}) {{ issue.title }}

```

**create/footer**
```
{{ if config.create.include_footer }}

### {{ config.create.footer_heading }}

{{  if config.create.milestone_replace_text
        replace_milestone_title config.create.footer_content config.create.milestone_replace_text milestone.target.title
    else
        config.create.footer_content
    end
end }}

```

When using this, in combination with a model/context similar to the following (**NOTE:** `issues`, `issuesDict`, `numberOfCommits`, `commitsLink`, `_targetMilestone`, `previousMilestone` haven't been shown for brevity):

```
var templateModel = new
{
    Issues = new
    {
        issues.Count,
        Items = issuesDict,
    },
    Commits = new
    {
        Count = numberOfCommits,
        HtmlUrl = commitsLink,
    },
    Milestone = new
    {
        Target = _targetMilestone,
        Previous = previousMilestone,
    },
    IssueLabels = issuesDict.Keys.ToList(),
};
```

And then rendering the template using the following:

![image](https://user-images.githubusercontent.com/1271146/103303102-0f77e000-49fd-11eb-90fa-e8a9a27ff57a.png)

The complete code can be seen in this [PR](https://github.com/GitTools/GitReleaseManager/pull/294)

It all works when using Scriban 2.1.4.  However, when trying to run the same code in 3.2.2, we get the following error message in one of our unit tests:

![image](https://user-images.githubusercontent.com/1271146/103303199-49e17d00-49fd-11eb-815c-df811562f42f.png)

```
 System.AggregateException : One or more errors occurred.
      ----> Scriban.Syntax.ScriptRuntimeException : resource://default/create/issue-details(3,30) : error : Cannot access target `issues.items` with a null indexer: issues.items[issue_label]
```

Do you have any suggestions about what needs to be changed in our current usage of Scriban to get this to work in 3.2.2?

Please let me know if you need any more details.

Adding @admiringworm for visibility.

**Comment by xoofx** [comment]
So there was one change with template when a target was null, it was running while now it will complain by default, so if you have `x.y` and `x` is null, it will generate an error, unless you specifiy `EnableRelaxedTargetAccess = true` on the `TemplateContext`

Could you try this to see if it passes more tests? (you might have to use your own derived `TemplateContext` in order to more easily control this.

I don't remember why I made this breaking change, it was 6 months ago and the development of 3.x was spawned other several months.

**Comment by xoofx** [comment]
Ooops, no, it's actually `EnableNullIndexer = true` on the `TemplateContext`

**Comment by xoofx** [comment]
Keeping `EnableRelaxedTargetAccess = false`  might be ok in your case.

**Comment by xoofx** [comment]
The case for `EnableNullIndexer = false` will trigger an error if `x[y]` and `y` is `null`. Previously, it was mixed with relaxed member.

**Comment by gep13** [comment]
@xoofx thank you very much!

This gets us a little further down the path...

If I add both of the suggested changes, I no longer get the exception being thrown, but the unit test still fails, due to the generated content not being equal to what is expected:

![image](https://user-images.githubusercontent.com/1271146/103304935-c8401e00-4a01-11eb-8431-597e237d4c82.png)

It is almost as though the model/context isn't being passed through to the child templates.  Is there another change that needs to be made to pass to the model/context through the various templates?

As I mentioned, this same test works when using 2.1.4:

![image](https://user-images.githubusercontent.com/1271146/103305066-240aa700-4a02-11eb-964a-47909b2f90dd.png)

**Comment by xoofx** [comment]
Hm, ok, so this is a regression in behavior... There was a change in the way loop variables are handled but it's definitely breaking the existing behavior. Let me check if I can find a fix.

**Comment by gep13** [comment]
That would be great! Do you have enough here to work with, or would a sample application help?

**Comment by xoofx** [comment]
> That would be great! Do you have enough here to work with, or would a sample application help?

I think I have enough, I will add a test to cover the regression you have discovered.

**Comment by xoofx** [comment]
This should be fixed by commit 4b316509c33db6da11e93b6c8a31e5c9e0badf60 and available in upcoming 3.3.0. Let me know if it is actually fixing your issue.

**Comment by gep13** [comment]
@xoofx thank you very much for fixing this so quickly!  I have just tested this locally on my machine, and all the Unit Tests are now passing 😄 I have kicked off a CI build [here](https://ci.appveyor.com/project/GitTools/gitreleasemanager/builds/37045403) which I expect will pass as well!  Thanks again, really appreciate your support here!

**Comment by gep13** [comment]
Yes, the CI build has passed, so I think we are good to close this out.

Thanks again!

**Comment by xoofx** [comment]
Great, thanks for reporting this! 😉
