### ISSUE TITLE
Request: add linked project in readme.md

### ISSUE THREAD

**Issue by NeilMacMullen** [scriban/scriban#294]
Firstly, thanks for a fantastic package! I've been looking for good templating engine to build on for years and Scriban hits all the right features.  I have used it to build an interactive templating application available from https://github.com/NeilMacMullen/Textrude .  If you think it appropriate, would you add it as one of your  related projects in your readme.md ?

**Comment by xoofx** [comment]
Sure, you can send a PR.

**Comment by NeilMacMullen** [comment]
Thanks ! :-)

Fixed in https://github.com/scriban/scriban/pull/301
