### ISSUE TITLE
Multiple MemberRenamers?

### ISSUE THREAD

**Issue by StefH** [scriban/scriban#305]
Is it possible to define multiple MemberRenamers ?

So the property `FooBar` can be accessed as:
- foobar
- fooBar
- FooBar
- foo_bar

**Comment by xoofx** [comment]
Not with `MemberRenamer`. There is not much documentation for this particular case but you would have to implement your own [IObjectAccessor](https://github.com/scriban/scriban/blob/770001d6f6092b22cf5f724fa9f9db8247eaaf83/src/Scriban/Runtime/IObjectAccessor.cs#L19) , hook [`TemplateContext.GetMemberAccessorImpl`](https://github.com/scriban/scriban/blob/770001d6f6092b22cf5f724fa9f9db8247eaaf83/src/Scriban/TemplateContext.cs#L781-L813) and return your own object accessor instance.  There are example of [accessors](https://github.com/scriban/scriban/tree/770001d6f6092b22cf5f724fa9f9db8247eaaf83/src/Scriban/Runtime/Accessors)...

But that can be laborious depending on how much you want to extend that (to ScriptObject, to .NET objects...etc.)
