### ISSUE TITLE
Multiple passes or lazy blocks

### ISSUE THREAD

**Issue by jods4** [scriban/scriban#306]
Is there any way one could write a template that would execute in two passes, or a template block that would execute after what comes next in the template?

To clarify: I would like to write a template that looks something like this:
```
Second pass: {{ lazy }}
{{- lazy = 2 -}}
```
And produces:
```
Second pass: 2
```

Here's a more real-world use case:
Say you want to produce a large JS module.
Along code generation you collect its dependencies.
At the end of generation, you want to add `import` statements at the top of file for those dependencies.

One way to achieve that that I have contemplated could be to generate a new template from the first one and execute that 2nd template. Although that would mean parsing every fully generated file (first passes), which doesn't sound very performant.

**Comment by jods4** [comment]
Instead of multiple passes, late binding would work as well:
```
Second pass: {{ capture-target lazy # names this block lazy, to be written to later }}
{{-
capture lazy
  2  # actually writes in the first block above
end
-}}

**Comment by xoofx** [comment]
No, there is no concept of multiple passes. You need to have things (functions, variables...) defined upfront, otherwise you would have to run the template twice, which you can perfectly do as well, but it's up to your requirements and workflow.

**Comment by jods4** [comment]
OK, I guessed so. Thanks for the fast response.

What about registering late-bound blocks that are filled later during 1st pass (as in my comment)? 
Would that be an interesting feature to add or is that too complicated?

**Comment by xoofx** [comment]
> What about registering late-bound blocks that are filled later during 1st pass (as in my comment)?
> Would that be an interesting feature to add or is that too complicated?

I think it's too niche and too much trouble to get this designed. For registering late bound, you can probably analyze the AST before rendering it, but it's again, very specific, depending on what you assume a block should not participate to the second pass (e.g your capture lazy block), so I think you can do it on your own by manipulating the AST:

- Parse to a Template1
- Extract the AST blocks from the Template1 and copy them to another empty Template2
- Remove the blocks extracted from Template1
- Run the Template1 first
- Run the Tempalte2 after with the same TemplateContext

**Comment by jods4** [comment]
How would I merge back the Template2 output into Template1 document?

For now, I'm doing a search-and-replace based on certain tokens in the generated output.
It works, but it's not ideal because it's C# code in my main program that's specialized for the template itself, meaning it's not possible for users to author new templates that would work in the same way.
With more effort I could generalize that, though.

**Comment by xoofx** [comment]
> How would I merge back the Template2 output into Template1 document?

Well, it's really up to your requirements. As I said, it's very unclear what you expect to be a "2nd-block", e.g how you would identify them. You will have to define some sort of rules in order to do that.

**Comment by jods4** [comment]
Sorry I expressed my question poorly.

Assuming I identify the blocks I'd like to fill in later, remove them from AST and run everything in two passes with separate templates as you suggested.

How would I do the final step, which is putting the output of Template2 into the output of Template1?
What Scriban structure should I touch to do that?

**Comment by xoofx** [comment]
> How would I do the final step, which is putting the output of Template2 into the output of Template1?
> What Scriban structure should I touch to do that?

I don't know, because I don't understand how you want to do that actually. How that would work. It's really up to you. Design wise, there are many things completely unclear that I can't give guidance.  Technically, you have access to the AST, you can do pretty much anything you want to separate things up-front, but that's not the problem here.

**Comment by jods4** [comment]
Thanks for the help.
By the way Scriban is great ❤️ 

I'll stick to my current solution for now.
Which is to put some marker in template `#LATER#`
Have the Scriban template generate some predefined variables with `capture Later; ....; end`
And finally my main program performs some replaces for those placeholders with the variables the template exported.

It's not the nicest for end-user but if the concept of "holes" that are filled later doesn't get into Scriban, I suppose that's the best I can do. It works anyway.

Thanks again.

**Comment by jods4** [comment]
Not sure if that's better but I just had another idea that doesn't require main C# program support (so it's self-contained in Scriban template).

Just run the "first pass" inside a `capture`.
Then write it wherever you need it.

Conceptually it's a bit backwards, but it does exactly what I want and it's not even that weird with the right variable names.

For example, if generating a JS file:
```
{{- capture jsCode -}}
template that generates JS code
{{- end -}}

// This is the final generated result
import {{ dependencies # this was computed during jsCode "first pass" above }};

{{ jsCode # output of "first pass" }}
```
