### ISSUE TITLE
Quoting strings in string array with built-in functions

### ISSUE THREAD

**Issue by patriksvensson** [scriban/scriban#310]
This is not really an issue, but more of a question.

I have a list of strings that I want to quote in my Scriban template.
Right now I'm doing this in my scriban template:

```liquid
public List<T> Foos { get; } = new List<T> {  {{ model.foos | array.join ", " };
```

Which does everything I want it to do, except it's not quoting each element:

```text
public List<T> Foos { get; } = new List<T> {  Foo, Bar, Baz };
```

My model looks like this:

```csharp
public sealed class Model 
{
    public HashSet<string> Foos { get; }
}
```

Is there a smart way of accomplishing the quoting with the built-in functions or will I have to provide my own function for this?

**Comment by xoofx** [comment]
Yeah, there is no nice map functions in scriban actually, but you can use something ugly like that:

```
public List<T> Foos { get; } = new List<T> {  {{ for $x in model.foos; if !for.first }}, {{end}}"{{ $x | string.escape }}"{{ end }} };
```

You can also workaround it like this (ugly as well)

```
public List<T> Foos { get; } = new List<T> {  {{ $x = model.foos | string.slice 1; $x | string.slice 0 ($x.size - 1)  }} };
```

Clearly there are some simple functions missing to handle such a case more nicely! 😉

**Comment by patriksvensson** [comment]
@xoofx Thank you. The code above will work perfectly for my use case!

Out of curiosity, if I would send a PR for something like this, how would you want it to work?

**Comment by xoofx** [comment]
> Out of curiosity, if I would send a PR for something like this, how would you want it to work?

Yeah thanks for proposing, I should be able to push a new API for that, that will be easier for me to do the change. But it will look probably something like that:

```
public List<T> Foos { get; } = new List<T> {  {{ model.foos | array.join ", " @string.literal }} };
```

**Comment by patriksvensson** [comment]
Awesome!

**Comment by xoofx** [comment]
So this should be fixed by commit aea92606a12da4b43de42112d2845b09f34eabb2 and available in 3.4.0. It has the following changes:

- New function [`array.each`](https://github.com/scriban/scriban/blob/master/doc/builtins.md#arrayeach)
- New function [`string.literal`](https://github.com/scriban/scriban/blob/master/doc/builtins.md#stringliteral)
- Add a new optional parameter to `string.join` to accept a function that will apply to the string element before joining (as in the above example)

Let me know if you encounter an issue with this.

**Comment by patriksvensson** [comment]
@xoofx Tested out the new `array.join` overload and it works like a charm! Thank you 👍🏻

**Comment by patriksvensson** [comment]
Also, really like how you put the commit in the follow-up message since it makes it easy for me to check what's changed and learn a bit about Scriban. I'm going to start doing that as well.

**Comment by xoofx** [comment]
> Also, really like how you put the commit in the follow-up message since it makes it easy for me to check what's changed and learn a bit about Scriban. I'm going to start doing that as well.

Yeah, usually I try to put the issue number in the commit message so the link is automatically created, but often I forget
