### ISSUE TITLE
TargetParameterCountException when rendering ValueKind or JObject

### ISSUE THREAD

**Issue by evolvedlight** [scriban/scriban#311]
Hi,

Latest Scriban, this is my test code to illustrate the issue.

I'm actually doing something else, but this is the same error.

```
static void Main(string[] args)
        {
            var input = JObject.Parse("{\"name\":\"steve\"}");
            var template = Scriban.Template.Parse("Hi {{name}}");
            var result = template.Render(input);
            Console.WriteLine(result);
        }
```

I get this:

System.Reflection.TargetParameterCountException: 'Parameter count mismatch.'

Am I doing something wrong here?

Thanks!

**Comment by NeilMacMullen** [comment]
I think your error is in expecting Scriban to turn a JObject directly into a model.  (Your model would actually be the internal structure of the JObject if it did work!) 

You'll need to walk the JObject tree to turn it into a suitable form...  the code here does that ...

https://github.com/NeilMacMullen/Textrude/blob/main/Engine/Model/Helpers/JsonGraph.cs

**Comment by xoofx** [comment]
JObject is not a supported model that you can use out-of-the-box. A better approach is to use what @NeilMacMullen is suggesting. You can also have a look at [similar code](https://github.com/xoofx/kalk/blob/45d102f680d54850f5ffe60e54d2b96255b1b20a/src/Kalk.Core/Modules/WebModule.cs#L381-L438) relying on `System.Text.Json`.

**Comment by evolvedlight** [comment]
@xoofx , @NeilMacMullen riiight, I see what I was doing wrong here, perfect. Just FYI I was actually trying to process JSON "shaped" input data - thought I had an `object `but actually it was a `JsonElement` so your code from kalk was actually exactly what I needed.

**Comment by NeilMacMullen** [comment]
@evolvedlight Not sure if you are trying to do the templating dynamically at runtime but for a static/compile time solution you can use my project https://github.com/NeilMacMullen/Textrude which does the model conversion for you.

**Comment by evolvedlight** [comment]
@NeilMacMullen something different actually (templating in office files), but I was just looking at Textrude now, I can see other uses for it!
