### ISSUE TITLE
Question: Terser function pointer syntax?

### ISSUE THREAD

**Issue by NeilMacMullen** [scriban/scriban#319]
I may be missing something but if i want to use a function pointer for a function that takes more than one argument I need to wrap the call in an anonymous function like...

```
func add(a,b) ;ret a+b; end
[1,2,3] | array.each @(do; ret add $0 3;end)
```
Is there a syntax that avoids the "do,ret,end" ceremony?  For example...

`[1,2,3] | array.each @(add $0 3)`

I don't think "@(" can prefix anything other than a function body?

**Comment by xoofx** [comment]
> I don't think "@(" can prefix anything other than a function body?

It can. What is in () is an expression that return a function. e.g It can reference an expression or an accessor that is actually going to be a function to call.

Note that when do comes last in an expression, it can be passed like this:

```
[1,2,3] | array.each do
  ret $0 + $1
end
```

Personally, I have been using Scriban without being much frustrated by that. The do syntax above usually covers most of the cases.

**Comment by NeilMacMullen** [comment]
Fair enough - I'm being a bit unreasonable trying to treat Scriban as a FP language ;-)

**Comment by NeilMacMullen** [comment]
Sorry - one other related question... Is there a way to pipeline across multiple lines (within a codeblock obviously) ?  E.g ...

```
[ 1,2,3]  |  array.filter @condition
             |  array.each @transform1
             |  array.each @transform2

```    


No problem if not - just wanted to make sure I'm not missing something.

**Comment by xoofx** [comment]
> Sorry - one other related question... Is there a way to pipeline across multiple lines (within a codeblock obviously) ? E.g ...

This should be possible in a recent version.
