### ISSUE TITLE
Evaluates properties even if they're not used in template text

### ISSUE THREAD

**Issue by alex-jitbit** [scriban/scriban#323]
My object has a property, based on `Lazy<T>` to prevent calling it unless it is needed.

But the property is always called by your renderer! Even if not used in the template text. Which eliminates the whole point of this.

Use case: the property is being read form the database and I don't want to do this unless required.

Any alternatives for lazy-initialization or "late-binding"?

Steps to repro:

```csharp
var template = Template.Parse("Hello, no templates here.");
var result = template.Render(new Tester());

public class Tester
{
	private Lazy<string> _prop;
	public string Prop { get { return _prop.Value; } }

	public Tester()
	{
		_prop = new Lazy<string>(() => MyMethod());
	}

	private string MyMethod()
	{
		return "test"; //<--- place breakpoint here - IT IS CALLED!!!!
	}
}
```

**Comment by xoofx** [comment]
That's because you put it as the root model, so it will force an import of the model.

Put it as a sub property of the model e.g:

```
var result = template.Render(new { model = new Tester() });
``` 

and you need to access it via `model.prop`

**Comment by alex-jitbit** [comment]
@xoofx thanks!
