### ISSUE TITLE
Should include pass the name of the first argument to the included template?

### ISSUE THREAD

**Issue by mwillebrands** [scriban/scriban#330]
Hi,

Before i'm going to create a pull request, i just wanted to verify the following with you.

When you create a template like this
`{{include 'myfunction' 'myparam'}}`

And the include looks like this
`{{$0}}`

Then i expect it to output *myparam*, as the included template might not now that it is included, however it outputs *myfunction*. In my opinion the first argument should not be passed to the template that is loaded by the include. What's your take on this?

Regards,
Maarten

**Comment by xoofx** [comment]
Yes, that's the actual behavior and we can't really change that as it would be a breaking change.
In 2.0, there was a bug and $0 was returning null, so in 3.x it is returning the parameters.
I also avoid to create a copy of the arguments when passing to include.
You could also imagine some code reacting to this include name...
