### ISSUE TITLE
Cannot load Scriban error in code generator

### ISSUE THREAD

**Issue by jpiquot** [scriban/scriban#335]
Hi,

It seems that there is an issue when using Scriban templating inside a C# 9.0 code generator. Rhe generator does not seem to be able to load Scriban DLL.

I don't have an error when using a manually loaded generator in a Unit test. Only when it's used in a project.

Reference to the generator in CSPROJ:
```
	<ItemGroup>
		<ProjectReference
			Include="..\..\..\Core\Bistrotic.Infrastructure.CodeGeneration\Bistrotic.Infrastructure.CodeGeneration.csproj"
			OutputItemType="Analyzer"
			ReferenceOutputAssembly="false" />
	</ItemGroup>
```

> 
> CSC : error BCG0001: Couldn't not generate code with code generator 'QueryCommandControllerGenerator'.
> 33>CSC : error : Could not load file or assembly 'Scriban, Version=3.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by xoofx** [comment]
Yes, it is a known issue with source generators (see [this](https://github.com/dotnet/roslyn/issues/49075)), not really the fault of Scriban but Source generators basically won't be able to load assemblies on the side.

You need to use scriban [source embedding](https://github.com/scriban/scriban#source-embedding) feature that was introduced to workaround this issue, as it will make Scriban sources being internal to your source generators.

**Comment by jpiquot** [comment]
Thanks, your solution works well!

**Comment by vova-lantsov-dev** [comment]
There is a good article regarding source generators, you can find the better solutions there instead of bringing the Scriban sources. Here is the link: https://turnerj.com/blog/csharp-source-generator-pain-points-february-2022-update
