### ISSUE TITLE
Evaluate returns ScriptArray instead of String

### ISSUE THREAD

**Issue by SvenMitlehner** [scriban/scriban#336]
`var so = new Scriban.Runtime.ScriptObject();`
`so.SetValue("X", "TEST", false);`
`var evaluated = Template.Parse("{{X}}").Evaluate(new TemplateContext(so));`

When run with Scriban <= 3.4.1 `evaluated` equals `TEST`, which is the expected result.
When run with Scriban >= 3.4.2 `evaluated` is a ScriptArray with four elements ('T', 'E', 'S', 'T').

(This might be a result of the modification made for this issue: https://github.com/scriban/scriban/pull/324)

**Comment by NeilMacMullen** [comment]
@SvenMitlehner   I don't think it was me - although possible I caused it indirectly by making @xoofx tweak around my PR.  Have raised PR https://github.com/scriban/scriban/pull/342 to address this - sorry for delay, only just saw this issue.

**Comment by binarycow** [comment]
@xoofx @SvenMitlehner  - I can't replicate; tested on `master`

```
var so = new Scriban.Runtime.ScriptObject();
so.SetValue("X", "TEST", false);
var evaluated = Template.Parse("{{X}}").Evaluate(new TemplateContext(so));
Console.WriteLine(evaluated?.GetType());
Console.WriteLine(evaluated);
```

Results in 

```
System.String
TEST
```

**Comment by xoofx** [comment]
>  I can't replicate; tested on

Yeah, that was fixed by @NeilMacMullen
