### ISSUE TITLE
Concrete Class will not map .... only Anonymous Type???

### ISSUE THREAD

**Issue by kvillines** [scriban/scriban#352]
The below code doesn't work but I believe that it should. When I create an anonymous type with the same property names than it works.

public void ReplaceTagsTest()
{
            EnrollModel enroll = new EnrollModel
            {
                Premium = "200",
                TypeofPlanSelected = "HMO",
                ApplicantFirstName = "Steven",
                ApplicantLastName = "Cryer",
                Medicareclaimnumber = "X484573HDGX"
            };
              
            var script = "Do you have the information from {{ApplicantFirstName}}  {{ApplicantLastName}} (’s) Medicare card available {{Medicareclaimnumber}}, Part A & B effective date?";
             
            var template = Template.Parse(script);
            var result =  template.Render(enroll);
        }

**Comment by binarycow** [comment]
Try this:

```
Do you have the information from {{applicant_first_name}}  {{applicant_last_name}} (’s) Medicare card available {{medicareclaimnumber}}, Part A & B effective date?
```

This is because of the default `MemberRenamer`.

> By default, Properties and methods of .NET objects are automatically exposed with lowercase and _ names. It means that a property like MyMethodIsNice will be exposed as my_method_is_nice. This is the default convention, originally to match the behavior of liquid templates. If you want to change this behavior, you need to use a MemberRenamer delegate

[Documentation](https://github.com/scriban/scriban/blob/master/doc/language.md#5-objects)
