### ISSUE TITLE
One TemplateContext & exception handling

### ISSUE THREAD

**Issue by szyb** [scriban/scriban#357]
Hi,

According to the docs `The TemplateContext provides: an execution context when evaluating a template. The same instance can be used with many different templates,`. So this is what I did, but there is an issue when first render fails with an exception. The second rendering will contain the output from the failed one (cut to the place where the error occurred).
Here is my code sample:
```csharp
  public static class ScribanFunctions
  {
    public static string PrintThisText(string text) => text;
  }
  class Program
  {
    static void Main(string[] args)
    {
      var scriptObject1 = new ScriptObject();
      scriptObject1.Import(typeof(ScribanFunctions));
      var context = new TemplateContext();
      context.PushGlobal(scriptObject1);
      try
      {
        var rendered2 = Template
          .Parse("This is call to non_existing_function and the result is `{{non_existing_function \"TEXT\"}}`")
          .Render(context);
        Console.WriteLine(rendered2);
      }
      catch (Exception ex)
      {
        Console.WriteLine($"Exception is {ex.Message}");
      }

      var rendered = Template
        .Parse("This is call to print_this_text and the result is `{{print_this_text \"TEXT\"}}`")
        .Render(context);

      Console.WriteLine(rendered);
    }
```

and the output is:
```
Exception is <input>(1,60) : error : The function `non_existing_function` was not found
This is call to non_existing_function and the result is `This is call to print_this_text and the result is `TEXT`
```
So the question is: am I doing it right and how should I handle exceptions to be able to reuse the context?

**Comment by szyb** [comment]
Yes, this is what I need. I missed casting to StringBuilderOutput. 
Thanks!

**Comment by binarycow** [comment]
Thanks @szyb - I think you identified the source of a bug I'm having on my application that uses Scriban.  The first render after an exception had extra output, but rendering again fixed the output... This is probably the reason why!

Thanks!
