### ISSUE TITLE
ternary operator precedence changed with 3.8.0?

### ISSUE THREAD

**Issue by SvenMitlehner** [scriban/scriban#360]
I was trying version 3.8.0 and stumbled upon a changed behaviour compared to 3.7.0 when using the ternary operator. 

I could not find any information about it in the changelog, so i assume it might not be an intended change. (I am aware of https://github.com/scriban/scriban/issues/355, but it seems to be a different problem)

Evaluating the template

`{{x = '3'; '1' | string.contains '2' ? '' : x}}`

gives the error message

`Invalid target function 3`

When adding brackets to the condition it works as expected

`{{x = '3'; ('1' | string.contains '2') ? '' : x}}`

Not using the variable x also evaluates without an error

`{{x = '3'; '1' | string.contains '2' ? '' : '3'}}`

The faulty template worked fine in 3.7.0

**Comment by xoofx** [comment]
Likely a regression not caught by tests. We will have a look (cc: @binarycow could have been introduced by some recent changes?)

**Comment by NeVeSpl** [comment]
That my fault, caused by  #344, x is detected as a function call and should be as variable.

**Comment by xoofx** [comment]
> That is my fault, caused by #344, x is detected as a function call and should be as variable.

Oh, ok, I'm going to revert it and publish a 3.8.1 in the meantime

**Comment by xoofx** [comment]
The revert should be available in a few minutes in `3.8.1`
