### ISSUE TITLE
Casting int as string

### ISSUE THREAD

**Issue by xuanzhan12** [scriban/scriban#364]
Hi, I'm trying to access a dictionary by an ID. I see that Scriban dictionary keys are strings. Is there a way to cast an int as string to access the value?

```C#
int MyInt = 1;
Dictionary<int, object> MyDict = new();
MyDict.Add(MyInt, new object());

string template = "{{ MyDict[MyInt] }}";
```

**Comment by xoofx** [comment]
Can you show the full code with the template parsing and rendering?

**Comment by xuanzhan12** [comment]
Here's the render method included.
```C#
int MyInt = 1;
Dictionary<int, string> MyDict = new();
MyDict.Add(MyInt, "hello");

string templateTxt = "{{ MyDict[MyInt] }}";

Template template = Template.Parse(templateTxt);
return template.Render(new { MyDict, MyInt }, member => member.Name);
```

Here it's easy to change the int to string before rendering, but in cases where MyInt is nested in some object I don't want to change the type because I'm doing some processing.

**Comment by xoofx** [comment]
Indeed, it was an original limitation, but recently indexer support has been added, so I have pushed a change in 7537754 to add support for this. 
It should be part of the upcoming `4.0.0+`
