### ISSUE TITLE
LoopLimit in TemplateContext

### ISSUE THREAD

**Issue by mominmaaz** [scriban/scriban#365]
Hi, First of all, Thanks for this amazing library. I just want to know why is there a need for LoopLimit in TemplateContext.cs?

**Comment by xoofx** [comment]
Scriban is a safe scripting language/engine that can be used directly by "end-users" and run on server-side. LoopLimit is a way to make sure that a user cannot go beyond a certain iteration limit for loops.

**Comment by mominmaaz** [comment]
Thanks for the reply. 

`Note that recently, a change was added so that if LoopLimit is set to 0, it will not apply any restrictions`

Exactly what I was expecting. Thanks again.
