### ISSUE TITLE
How to resolve variable from TemplateContext?

### ISSUE THREAD

**Issue by fuzzykiller** [scriban/scriban#371]
I’m looking to write a custom function that would access a global variable that is present on the stack. (So the template can stay relative clean.)

On `TemplateContext`, I can access to topmost object (`CurrentGlobal`), but is it also possible to just get a variable by name or perhaps even type (with some custom code, of course)?

Thanks in advance!

**Comment by xoofx** [comment]
Could `TemplateContext.GetValue` be fine for your use case?

https://github.com/scriban/scriban/blob/486ae53003f3e9775d25a856f80cb28ca3b55e84/src/Scriban/TemplateContext.Variables.cs#L262

**Comment by fuzzykiller** [comment]
Yes I found this method, but I’m unsure how to use it. Can I really just do `new ScriptVariableGlobal("myVar")` and stick it in `TemplateContext.GetValue` and that’ll “always” work?

**Comment by xoofx** [comment]
It should yes, that's what is used within the engine.

**Comment by fuzzykiller** [comment]
Okay, awesome. Thank you very much for the quick reply!

**Comment by BenJBailey** [comment]
Thanks! This was incredibly helpful. 

It would be helpful to have something like this in the docs. It took me a while to figure this out. I realize it's a lot of work to keep docs up to date.

**Comment by BenJBailey** [comment]
Added a pull request to update docs  #545
