### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by mikechristiansenvae** [scriban/scriban#372]
I'd like to have support for namespaces (like in XML) in Scriban.

Right now, "names" in Scriban are _really_ just string values.  

So, if I had to implement this on my own, I would make a function `make_name(string namespace, string name)` that returns a name in "[Clark Notation](http://www.jclark.com/xml/xmlns.htm)".  

For example, the HTML `h1` element:

```
make_name "http://www.w3.org/1999/xhtml" "h1"
```

results in

```
"{http://www.w3.org/1999/xhtml}h1"
```

Then, this can be looked up just like normal, assuming that someone didn't just happen to make their object name `{http://www.w3.org/1999/xhtml}h1`.

----

I know its a **long shot**, but.... My suggested change would be making this functionality a first-class feature in Scriban.

For runtime support, we'd need to change `IScriptObject` to handle namespaces... For example:

- `bool Contains(string namespace, string member)` 
- `void SetReadOnly(string namespace, string member, bool readOnly)`
- We could use extension methods, so that when you call `scriptObject.Contains("memberName"), it calls `scriptObject.Contains(string.Empty, "memberName")`
- `this[string namespace, string member]` (getter/setter)

(Obviously, we'd need to adjust all the calling code as well...)

Language support's gonna be the hard one.  We could do something similar to XML...

```
{{
namespaces.default_namespace "http://www.w3.org/1999/xhtml"
namespaces.add_prefix "svg" "http://www.w3.org/2000/svg"

# Returns the value of `my_globals["http://www.w3.org/1999/xhtml", "h1"]
my_globals[h1]

# Returns the value of `my_globals["http://www.w3.org/2000/svg", "circle"]
my_globals[svg:circle]
}}
```

**Comment by xoofx** [comment]
Thanks for the proposal but I will have to decline it.

Reason is that today, this concept is already provided by sub objects, like for builtin functions when you do a `string.pad_left`, `string` acts as a kind of namespace. you can even import it via `import string`

Introducing another concept here would be very confusing and would not bring enough value other the solution that is existing.
