### ISSUE TITLE
Cannot get the member for a null object

### ISSUE THREAD

**Issue by richard-browne** [scriban/scriban#375]
I'm trying Scriban with ParseLiquid() to attempt to render existing templates. I get this error in a number of places:

> Cannot get the member a.b.c for a null object

The problem is if statements such as this in the template:

```
{% if a.b.c and a.b.c != 0 %}
 ...
{% else %}
 ...
<% endif %}
```

When a.b is null, Liquid does not throw an error and evaluates to false (executes the 'else' block). In Scriban it throws the above error.

**Comment by xoofx** [comment]
Don't have access to a computer, but I believe you might be misusing the liquid setup in Scriban. Could you post a sample program showing how you parse and run the template?

**Comment by richard-browne** [comment]
Hi thanks for the reply. I fixed my issue by using LiquidTemplateContext instead of TemplateContext. Then the beviour is compatible and the exception is not thrown. It's not mentioned in the documentation that you need to use LiquidTemplateContext. I only figured it out by browsing the scriban source code.

**Comment by xoofx** [comment]
Yes, the Template class is wrapping some logic for easy templating for Liquid. `LiquidTemplateContext` is not super documented as I explained in the other issue #374 as I don't encourage to use Liquid with Scriban.
