### ISSUE TITLE
[feature request] ability to default encode for html 

### ISSUE THREAD

**Issue by John0King** [scriban/scriban#388]
I post it  in #137  earlier,  but it is closed.

@xoofx   does this being supported now ?

 I know `scriban` may not only output html, so make it  like razor may not an reasonable change,   but  we should open this ability, because we need `{{ $myHtml | raw}}`  when we make it default to Encoded html.

we can add an `IRawContent`  like razor's `IHtmlContent` , with that we can add the `raw`  filters as an build-in filter
then we add an option `Func<string,IHtmlContent> OutputAction`  , then we can happy coding.

```C#
TemplateContext  context = GetTemplateContext();
// the default OutputAction is   str=> new RawContent(str);

context.OutputAction = str=> new RawContent(WebUtility.HtmlEncode(str)); //default for html

// then renderContent
```

```html
<div class="article-content">{{ model.content | raw }}</div>
```

and the buildin `raw` filter with C# implement
```c#
IRawContent Raw(string str)
{
    return new RawContent(str);
}
```

that way we can be safe for both the default and the changed encoded output.

and we default for JavaScript too
```C#
context.OutputAction = str=>new RawContent(JavaScriptEncoder.Default.Encode(str));
```

**Comment by John0King** [comment]
@xoofx that break  `html.escape`  😂

**Comment by matteocontrini** [comment]
> Right, but overriding `TemplateContext.Write` can be used exactly for this kind of scenario:
> 
> ```cs
>     public class MyTemplateContext : TemplateContext {
>         public override TemplateContext Write(SourceSpan span, object textAsObject)
>             => base.Write(span, textAsObject is string text ? WebUtility.HtmlEncode(text) : textAsObject);
>     }
> ```

For anyone trying this solution and finding out it doesn't work: make sure you override `WriteAsync` if you're using asynchronous template rendering.
