### ISSUE TITLE
math.format "C" not always a dollar sign

### ISSUE THREAD

**Issue by hoppities** [scriban/scriban#390]
We're using Scriban for a dynamic templating system, and periodically, we'll get ¤ rather than $ when formatting dollar amounts. It would seem that our CurrentCulture info is `en-US`.

Any ideas why this would happen? Is this a Scriban configuration problem or do you think we should look elsewhere?

**Comment by xoofx** [comment]
Nope, can't tell. When you say periodically, like on your own machine, or on a random CI machine that could get different locale?
