### ISSUE TITLE
Unable to cast object of type 'Scriban.Syntax.ScriptIfStatement' to type 'Scriban.Syntax.ScriptElseStatement'.

### ISSUE THREAD

**Issue by Kavalan12** [scriban/scriban#393]
The following scriban template breaks the Template.Parse() and throws an exception:

```
{{ 
  for $s in Foo
      {{ if $s
          false
      else if $s
          false
      end
  end 
}}
```

Unable to cast object of type 'Scriban.Syntax.ScriptIfStatement' to type 'Scriban.Syntax.ScriptElseStatement'.

I know the scriban is not valid, but I thought the Template.Parse() is supposed to set the boolean HasErrors to true when the parsing failed and not throw an exception.

**Comment by xoofx** [comment]
Fixed by commit 871d746
