### ISSUE TITLE
[Question] Strict property check

### ISSUE THREAD

**Issue by HamedFathi** [scriban/scriban#396]
Hi,

Is it possible to get an error when a property does not exist in an object?

```
<ul id='people'>
  {{ for person in people }}
    <li>
      <h2>{{ person.name }}</h2>
           Age: {{ person.age }}
           {{ person.family_nam | string.truncate 5 }}
    </li>
  {{ end }}
</ul>
```

`family_nam` is wrong (does not exist/miss-spelling) but the template engine just ignores it. Is it possible to have a strict option to raise an error?

**Comment by xoofx** [comment]
Setup `TemplateContext.EnableRelaxedMemberAccess` to `false`

https://github.com/scriban/scriban/blob/6ec9d838343379363ed22e3fb30fd3a38491b1d9/src/Scriban/TemplateContext.cs#L376-L379

By default it is `true` in `TemplateContext` constructor:

https://github.com/scriban/scriban/blob/6ec9d838343379363ed22e3fb30fd3a38491b1d9/src/Scriban/TemplateContext.cs#L121
