### ISSUE TITLE
StrictVariables does not apply to hierarchy 

### ISSUE THREAD

**Issue by sintak123** [scriban/scriban#402]
Hi, 

thank you for writing and maintaining this cool library. 
We are using it in our company and I would like to report a bug. 
If it could not be fixed soon, I would very appreciate if you could suggest a workaround. 

**Bug Description** 
When a template contains hierarchical key (like _Property.Name_) the StrictVariables applies only to the first part of the key (_Property_), but not to the subsequent parts (_Name_).

**Current Behavior** 
Instead of throwing an exception, an empty string is inserted.

**Expected Behavior**
An exception is thrown.

**Unit Test**

```
[Test]
public void Hierarchy_Does_Not_Apply_StrictVariables()
{
	var templateText = "Hi {{Property.NameX}}!"; // No such a property.
	var model = new
	{
		Property = new { Name = "Joe" }
	};
	var template = Template.Parse(templateText, "Test");
	var scriptObject = new ScriptObject();
	scriptObject.Import(model, renamer: member => member.Name);

	var context = new TemplateContext
	{
		StrictVariables = true,
		MemberRenamer = member => member.Name
	};

	context.PushGlobal(scriptObject);

	Assert.Throws<Exception>(()=> template.Render(context));
	//Message:
	//Expected: < System.Exception >
	//But was: null
}
```
 Thank you again for your effort.

Kristijan

**Comment by xoofx** [comment]
The documentation hasn't been updated, but many features have been introduced to the `TemplateContext` in Scriban 4.x+ to allow such scenarios (e.g `EnableRelaxedTargetAccess` or `EnableRelaxedMemberAccess`)

https://github.com/scriban/scriban/blob/90c9e3dde96bfca858763ee88a0bffe4a9dfe121/src/Scriban/TemplateContext.cs#L361-L394
