### ISSUE TITLE
Access to function with same name in different class

### ISSUE THREAD

**Issue by Andres128** [scriban/scriban#403]
Hello great library thanks!!!, i have a problem. 

I have two different class FuncA and FuncB with same function name Hello

```
public class FuncA
{
	public static string Hello()
	{
		return "Hello A";
	}
}
public class FuncB
{
	public static string Hello()
	{
		return "Hello B";
	}
}
```
Now i need access to function Hello: {{FuncA.Hello}} {{FuncB.Hello}}

```
ScriptObject scobj = new ScriptObject();
scobj.Import(typeof(FuncA), null, x => x.Name);
scobj.Import(typeof(FuncB), null, x => x.Name);

TemplateContext context = new TemplateContext();
context.PushGlobal(scobj);

Scriban.Template parse = Template.Parse("FuncA: {{FuncA.Hello}} | FuncB: {{FuncB.Hello}}");
string result = parse.Render(context);

MessageBox.Show(result);
```

NOT working i have a error: **Cannot get the member FuncA.Hello for a null object.**

How solve this??? Bye and thanks...

**Comment by xoofx** [comment]
You are not using the bindings correctly. Nor `FuncA` or `FuncB` are accessible. You are just importing two times the same function `Hello` that will be accessible from the template. You can read more details in the documentation about what are the defaults.


Something along these lines should be closer to what you are looking for:

```c#
ScriptObject scobj = new ScriptObject();

var funcA = new ScriptObject()
funcA.Import(typeof(FuncA), null, x => x.Name);
scobj.Add("FuncA", funcA);

var funcB = new ScriptObject()
funcB.Import(typeof(FuncB), null, x => x.Name);
scobj.Add("FuncB", funcB);

TemplateContext context = new TemplateContext();
context.PushGlobal(scobj);

Scriban.Template parse = Template.Parse("FuncA: {{FuncA.Hello}} | FuncB: {{FuncB.Hello}}");
string result = parse.Render(context);
```
