### ISSUE TITLE
html.strip cause regex timeout on bad  tags

### ISSUE THREAD

**Issue by daniel-johnsson** [scriban/scriban#406]
Text that opens a tag with `<`and includes several `=` and never closes will cause a regex timeout. 
example text
``` 
<a=b=c=d=e=f=g=h=i=j=k=l=m=n.....
```

**Comment by xoofx** [comment]
It could definitely be, the code that is parsing this is here:

https://github.com/scriban/scriban/blob/78de3af89c0c1bcca04bbb228df4008a077d1164/src/Scriban/Functions/HtmlFunctions.cs#L21-L46

Don't have time allocated personally to fix this issue, but PR welcome.

**Comment by xoofx** [comment]
Closing as `won't fix` as a regular expression will never be reliable for a safe strip.
Added a documentation note in the commit a3c7b07 with a workaround.
