### ISSUE TITLE
Math issue with floating point: 1.01 + 1.1 = 2.1100000000000003 ?

### ISSUE THREAD

**Issue by fabriciomurta** [scriban/scriban#408]
I think the title talks for itself, but here's a bit more about it:

This can be reproduced by using this expression at [the scriban demo page](https://scribanonline.azurewebsites.net/):

```
{{ 1.01 + 1.1 }}
```

This is the simplest form and I only couldn't reproduce it if either member in the math is a rounded integer (e.g. `1.0 + 1.1`, `1.01+1.0`).

I know I can just use `math.round()` but... I am not sure I should. :)

**Comment by fabriciomurta** [comment]
I see that this comes down from javascript and C# (at least for .NET 6 -- although not really .NET 4, interestingly) so that's probably a much bigger problem than first thought.

Should we expect a programmer's math, or a calculator's math in Scriban?

In one hand, Scriban is a programming language. But in the other one it is intended for text templating...

**Comment by xoofx** [comment]
> Should we expect a programmer's math, or a calculator's math in Scriban?

It's programmer's math by default. You need to use the postfix `m` to switch to precise decimal calculation:

```
{{ 1.01m + 1.1m }}
```

**Comment by fabriciomurta** [comment]
nice! In case somebody else bumps into this [.NET floating point numeric types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types) has some more insight on `System.Decimal` in .NET.
