### ISSUE TITLE
Accessing AST through callerContext

### ISSUE THREAD

**Issue by zacbre** [scriban/scriban#41]
https://github.com/lunet-io/scriban/issues/19#issuecomment-289989547

Accessing the AST was mentioned here in this post above, but I'm not too sure how it can be accessed after messing around with it for a few hours.

Basically, I'm looking to restrict an IScriptObject from running unless it's located inside of an if statement, like such:

```
{{ if has_item }}
     {{ object.get_value }}
{{ else }}
     static value
{{ end }}
```

(has_item is a IScriptCustomFunction)

I'd like to prevent object.get_value from being called unless it's inside of a {{ if has_item }}

Is this possible with Scriban?

Thank you!

**Comment by xoofx** [comment]
Unfortunately, this is not possible. The AST doesn't provide a way to navigate upward (parent expression/statements)

**Comment by xoofx** [comment]
This has been fixed. `TemplateContext.CurrentNode` and `ScriptNode.Parent` have been introduced.
