### ISSUE TITLE
Add string.index_of

### ISSUE THREAD

**Issue by mikechristiansenvae** [scriban/scriban#413]
Suggest adding built-in functions that mirror the .NET method `String.IndexOf` [(docs)](https://docs.microsoft.com/en-us/dotnet/api/system.string.indexof?view=net-6.0#system-string-indexof(system-string-system-int32-system-int32))

Request that parameters be included that support (at least) the usage of all three of these overloads:

- `public int IndexOf (string value);`
- `public int IndexOf (string value, int startIndex);`
- `public int IndexOf (string value, int startIndex, int count);`

**Comment by xoofx** [comment]
Agreed, in Scriban that would require to declare it in a single method in [StringFunctions](https://github.com/scriban/scriban/blob/master/src/Scriban/Functions/StringFunctions.cs), PR welcome.

```
public static int IndexOf (string text, string search, int? startIndex, int? count = null);
```

**Comment by binarycow** [comment]
@xoofx : https://github.com/scriban/scriban/pull/415
