### ISSUE TITLE
[Feature] Filtered loops

### ISSUE THREAD

**Issue by jods4** [scriban/scriban#417]
Scriban has support to reverse and limit (take/skip) loops.

It would be lovely if it also add a syntax to filter the elements being iterated (basically calling `.Where()` on the `IEnumerable` / `IQueryable`) being iterated.

Something like: 
```
for name in people where:($0 | string.starts_with "H")
```

**Comment by xoofx** [comment]
Yep, it's a feature that was also mentioned in the past #73 

I'm not sure about the design, because making it only relevant for loops might not be the best approach and I don't know if that would require a specific support from the language or if that could be implemented entirely through regular functions.

**Comment by xoofx** [comment]
Note that today you can already do something like this with anonymous function:

```
for name in people | array.filter @(do; ret $0 | string.starts_with 'H'; end)
```

It's just that the syntax is a bit more verbose.

**Comment by jods4** [comment]
Yeah the `@` and `do; end` syntax is not the most pretty.

Also using `array.filter` has a side-effect of buffering everything.
If `people` is `IEnumerable`, you can observe that the enumerable has been _entirely_ consumed (with any associated side-effect) when the loop body _first_ executes.

This is just quality of life of course, but I feel that for a scripting language that prints data, easily filtering its input should be a common scenario.

For now, my go-to solution is a `if` with `continue`:
```
for name in people
  if !string.starts_with name "H"; continue; end
end
```

**Comment by MRIIOT** [comment]
> `for name in people | array.filter @(do; ret $0 | string.starts_with 'H'; end)`

What would this syntax look like if it's an array of ints and I wanted to filter out all zeros?

**Comment by sekalek** [comment]
Hi
I have problems with filtering loop.
My template

`  {{ for h in HEADER }}
  {{ h.DocID }}
    {{ for r in ROWS
    if r.DocID != h.DocID
    continue 
    end
    }}
  {{ r.DocID }}
  {{ r.RowID }}
  {{ if for.last }} last {{ end }}
  {{ end }}
  {{ end }}`

How to filter ROWS for correct detect last record ?
