### ISSUE TITLE
Having difficulties in rendering template with a model having a collection.

### ISSUE THREAD

**Issue by mkgn** [scriban/scriban#419]
I was initially using RazorEngine and then thought to give Scriban a try. What I was trying to do is to simply render below data

            var reportData = new List<MyReportDto>
            {
                    new MyReportDto
                    {
                        City = "City",
                        ColorCode = "Blue"
                    }
            };

In code I get the rendered data as below;

            string content = File.ReadAllText(Path.GetFullPath("Templates/my_scriban_template"));
            var result = await Scriban.Template.Parse(content).RenderAsync(reportData);

Then the rendered result string will be sent to a view where it will render it using razor @Html.Raw()

My template file is:

    <div class="row">
    <div class="col-md-12">
        <h3>Action Plan By Month Report</h3>
    </div>
    <div class="col-md-12">
    {{report_data.empty?}}
        <table>
            <tr>
                <th>Year</th>
                <th>Month</th>
                <th>Group</th>
                <th>Action Plan</th>
                <th>Status</th>
            </tr>
            {{ for item in report_data }}
                <tr>
                    <td>2022</td>
                    <td>Jan</td>
                    <td>{{item.city}}</td>
                    <td>{{item.color_code}}</td>
                </tr>            
            {{ end }}
        </table>
    </div>
</div>

The problem is no data is rendered. If I use a simple object such as;

             var reportData = new MyReportDto
            {
                City = "City",
                ColorCode = "Blue"
            };

and if I use

{{color}}
{{color_code}}

it prints the values.

As per the documentation my property naming conventions seems to be correct. So I am not sure what I am doing wrong here.

**Comment by xoofx** [comment]
Change this line to:
```
     var result = await Scriban.Template.Parse(content).RenderAsync(new { reportData });
```

You have to pass a model that has the report_data variable, otherwise that won't work.
