### ISSUE TITLE
Null-safe navigation should be right-associative

### ISSUE THREAD

**Issue by jods4** [scriban/scriban#427]
This code is never gonna work: 
```
a?.b.c == 42
```
The problem is that it is evaluated as `(a?.b).c` and when `a` is null the expression `(null).c` fails.

operator `?.` is much more useful if it is evaluated as `a?.(b.c)` if that makes sense as pseudo-syntax.
It's how C# does it: once something is null on the left of `?.` all properties on the right are dropped.

As is, the workaround is to include `?.` on every property access after the first: `a?.b?.c?.d`, even if `c` is never null on a `b` instance.

**Comment by xoofx** [comment]
Fixed by commit 3439652, will be available in next version
