### ISSUE TITLE
Question: How to cast splitted array string to number ?

### ISSUE THREAD

**Issue by reaby** [scriban/scriban#432]
I've tried and tried, either it doesn't work or i'm no unable to do this right. I'm btw using Liquid parser and context.

So how to do this right, let's assume `pos` is a a string "0 12".

```xml
{% assign arr = pos|split(" ") %}
{% assign div = (arr|last)|string.to_int %}
<frame pos="{{arr|first}} {{ div|math.is_number }}">
         <!-- other code -->
</frame>
```

Returning:

```xml
<frame pos="0 false">
         <!-- other code -->
</frame>
```

Thing is I would need to do rather simple math with the numbers from this position to place the buttons etc elements (in a loop) to rows and columns. I don't get why it doesn't cast the string to number.

So i'm not sure if this is a bug in Scriban or is it just me incapable of doing this right...

**Comment by xoofx** [comment]
The `string` or `math` objects are not accessible in Liquid by default. You would have to import the objects (copy them from a Scriban context to liquid context)

**Comment by reaby** [comment]
Thanks!
Got it working now, closing issue for solved.
