### ISSUE TITLE
Unexpected whitespace when auto indentation is enabled

### ISSUE THREAD

**Issue by mihe** [scriban/scriban#435]
First of all, thanks for a great templating library!

Upgrading from version `5.2.0` to `5.3.0` (or later) seems to result in changes in my rendered output that don't seem quite right, even when factoring in the new `TemplateContext.AutoIndent` flag. Disabling said auto indentation does fix the issue though, and serves as a workaround for now.

I've tried reducing the template as best I can. Any further changes I do to it seems to result in correct output.

**Template**:
```
[
  {{~ for i in 1..2 ~}}
  [
    {{~ for j in 1..3 ~}}
    {{~ if true ~}}
    Lorem ipsum dolor {{"sit"}} {{"amet"}}.
    {{~ else ~}}
    Ut enim ad minim veniam.
    {{~ end ~}}
    {{~ end ~}}
  ]
  {{~ end ~}}
]
```

**Expected output**:
```
[
  [
    Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet.
  ]
  [
    Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet.
  ]
]
```

**Actual output**:
```
[
  [
    Lorem ipsum dolor sit  amet.
    Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet.
  ]
  [
    Lorem ipsum dolor sit  amet.
    Lorem ipsum dolor sit amet.
    Lorem ipsum dolor sit amet.
  ]
]
```

Note the extra space before "amet" on the first line of every block.

**Comment by xoofx** [comment]
Thanks! That should be fixed by commit b849c54 and available in `5.4.6+`
