### ISSUE TITLE
How to lazy load a variable in context

### ISSUE THREAD

**Issue by ste-bel** [scriban/scriban#437]
I put some query results in my context but they might take a long time to run. What's the best way to put them as a lazy reference and only execute the query when the variable is accessed so the reference in the context is replaced by the query result?

**Comment by mingmoe** [comment]
I think function will be a good choice.
```C#
var scriptObject1 = new ScriptObject();
// Declare a function `myfunc` that cost long time to process
scriptObject1.Import("myfunc", new Func<string>(() => {Thread.Sleep(1000); return "done"; }));

var context = new TemplateContext();
context.PushGlobal(scriptObject1);

var template = Template.Parse("This costs looooong time: `{{myfunc}}`");
var result = template.Render(context);

// Prints: This is myfunc: `done`
Console.WriteLine(result);
```
https://github.com/scriban/scriban/blob/master/doc/runtime.md#imports-a-net-delegate

Function only was called when it was used.

**Comment by xoofx** [comment]
Yeah, you can use a function instead and this function can wait on e.g a Lazy variable and would wait on the result to be computed

**Comment by ste-bel** [comment]
Thank you so much guys, I was thinking of that but wasn't sure how to put it in the context. I just love Scriban and have been using it for multiple projects.
