### ISSUE TITLE
Question: How to link a CSS file in a .scriban-html document?

### ISSUE THREAD

**Issue by jaidenbm0127** [scriban/scriban#440]
Just started using the Scriban engine and was trying to get an external CSS file attached to the template. Is this possible or does the styling need to be internal only? I tried linking it the via the <link> tag but it didn't work unless I just used a <style> tag in the html. 

Sorry if this is a potentially dumb question, I may just be misunderstanding something that's very obvious to some.

**Comment by xoofx** [comment]
Not sure what is your use case, but Scriban is a templating engine that you need to use in your own C# code to transform it to e.g html. Then "linking" it to some css file is up to your application. CSS is a concept completely unknown to Scriban and HTML as well.
