### ISSUE TITLE
object.eval with additional newline

### ISSUE THREAD

**Issue by klauswiesel** [scriban/scriban#441]
Hi

I am using Scriban with a custom object that contains basically labels. 

Lets say I have the object  Labels = { Label1: "L1", Label2: "L2"}

I can use {{ Labels.Label1 }} and are getting the correct value "L1"

As we want some custom labels which are not known at runtime, we have a local object 
custom: [
{key: "Labels.Label1", value: "C1"}
]

Now I have a function that looks into the custom array and tries to find an entry, and if nothing is found, it evaluates the given "item" using object.eval.

When I call 

"Labels.Label1" | label ":"

I get "L1:" back, note that the  colon is directly behind "L1"

When I call 

"Labels.Label2" | label ":"
I get "L21:" back, note that the  colon is in a new line behind "L2"

Why is this happenng?

```
{{func byKey(label)
   ret label.key == key 
end}}

{{func label(item, suffix = "")

    key = item
    labelObject = custom | array.filter @byKey
    if labelObject.size == 1 
        ret (labelObject[0].label) + suffix
    else
        ret (item | asString) + suffix
    end
end
}}

```

**Comment by xoofx** [comment]
I don't see any `object.eval` in your sample. Could you post a small unit test that replicates exactly the problem that I could have look at?

**Comment by klauswiesel** [comment]
Sorry, forgot this:
{{ func asString(item)
    ret ((item | object.eval) | string.strip)
end }}

**Comment by klauswiesel** [comment]
Sorry for not posting a reproducalbe test.
I tried around a little and found that  the resulting html is broken:

I am showing the result of the label  function in a div and found that the output is like this for the case "L1":
<div>L1:</div>
But for "L2" I am getting 
L2<div>:</div> 
Which looks as if a newline was added

**Comment by xoofx** [comment]
This code gives the correct output (I removed the `labelObject.size == 1` because this one feels unclear to me and how the model is done)

Eval is working fine here, so I doubt this is the problem:

```c#
        [Test]
        public void TestObjectEval()
        {
            var input = @"{{func byKey(label)
   ret label.key == key 
end
func label(item, suffix = """")

    key = item
    labelObject = custom | array.filter @byKey
    ret (item | asString) + suffix
end
func asString(item)
ret ((item | object.eval) | string.strip)
end
~}}
{{""Labels.Label1"" | label "":""}}
{{""Labels.Label2"" | label "":""}}
";
            var template = Template.Parse(input);
            var result = template.Render(new
            {
                custom = new ScriptArray()
                {
                    new ScriptObject()
                    {
                        { "key", "Labels.Label1" },
                    },
                    new ScriptObject()
                    {
                        { "key", "Labels.Label2" },
                    },
                },
                Labels = new ScriptObject()
                {
                    {"Label1", "L1"},
                    {"Label2", "L2"},
                },
            }, memberRenamer: x => x.Name);
            Console.WriteLine(result);
        }
```

**Comment by klauswiesel** [comment]
Let me explain the usage scenario:

We have a data property Labels that comes in from the calling environment, this contains our default labels.
It has the following content: 
"Labels.Labels1" = "L1" and "Labels.Labels2" = "L2"

In the template, we allow to define some labels that can overwrite the default ones. 
Therefore I had the custom array.
"Labels.Labels1" = "C1" 

Now, when "label" is called with lets say "Labels.Label1", I want to check if this is contained in the custom array, when yes, I want the custom value (this was the line you removed). This part is working fine for me. 

The problem arises when the parameter to "label" is not found in custom array. Then I know, that the parameter "item" itself contains the name of the data property given into the template from our backend. And in this case, there is a problem:

I looked into the html that is generated in the end and found that there is a problem there in the second case. As this editor does not allow entering html as text, I added a screenshot of the resulting html. Hope this helps.

![image](https://user-images.githubusercontent.com/31765206/174246394-a72e4186-2449-460e-a6ee-52ef2da1cac2.png)

**Comment by xoofx** [comment]
Thanks for the explanation, but what I see is an output, but I don't see why it is failing. Eval is working fine in the case as I showed above, so a reproducible small program is necessary because I'm missing something here. You are mentioning a newline problem with eval, I don't see this correctly explained.

Note, this editor allows to enter html text 😉 

```html
<div>C1:</div>
L2<div>:</div>
```

**Comment by klauswiesel** [comment]
We will try to put something together on your basis. Thanks so far
