### ISSUE TITLE
Undefined variables are not handled

### ISSUE THREAD

**Issue by benjaminbosko** [scriban/scriban#443]
Hi,

The following code snippets from the documentation are not working:
[Input](https://github.com/scriban/scriban/blob/master/doc/language.md#:~:text=multiline%20statements):
```
{{
  if !name
    name = "default"
  end
  name
}}
```
Expected output: `default`
Actual output:
```
Failed to render text '{{
  if !name
    name = "default"
  end
  name
}}
' at template.
 ---> <input>(7,7) : error : The variable or function `name` was not found
```

[Input](https://github.com/scriban/scriban/blob/master/doc/builtins.md#:~:text=%7B%7B%20undefined_var%20%7C%20object.default%20%22Yo%22%20%7D%7D): `{{ undefined_var | object.default "Yo" }}`
Expected output: `Yo`
Actual output:
```
Failed to render text '{{ undefined_var | object.default "Yo" }}' at template.
 ---> <input>(7,3) : error : The variable or function `undefined_var` was not found
```

Could you check them?
Thank you in advance!

**Comment by benjaminbosko** [comment]
As a workaround I was able to use it:
```
{{
  if !this.name
    name = "default"
  end
  name
}}
```

**Comment by xoofx** [comment]
The following code returns the proper result, so you are doing something different here that you don't show in your issue:

```
[Test]
public void TestEmptyVar()
{
    var input = @"{{
      if !name
        name = ""default""
      end
      name}}";
    var template = Template.Parse(input);
    var result = template.Render();
    // prints "default"
    Console.WriteLine(result);
}
```
