### ISSUE TITLE
Render to Stream/FileStream

### ISSUE THREAD

**Issue by Jasonkingsmill** [scriban/scriban#447]
Hi,

We have a requirement for embedding fairly large base64 encoded strings (large files) inside rendered output (could be in the vicinity of 30-40mb each).
Since the template rendering returns a string, we suffer memory pressure due to the entire base64 contents in memory twice - once for the input, once as part of the output string.

What I'd like to do is allow rendering directly to FileStream rather than returning a string.

Additionally, allowing model properties to be read from stream would also be greatly beneficial.

Is this at all possible?

**Comment by xoofx** [comment]
For large output/streaming, it's possible, see [this comment](https://github.com/scriban/scriban/issues/54#issuecomment-389666169).

> Additionally, allowing model properties to be read from stream would also be greatly beneficial.

I don't think that Scriban should provide such a built-in thing, as it is very app specific (another person could start to come with e.g "I want to read properties from a socket or a pipe or a database...").
That being said, a scripting object in Scriban is abstracted via the interface [`IScriptObject`](https://github.com/scriban/scriban/blob/master/src/Scriban/Runtime/IScriptObject.cs), so you could develop an implementation that fits exactly what you are looking for.

**Comment by Jasonkingsmill** [comment]
> For large output/streaming, it's possible, see [this comment](https://github.com/scriban/scriban/issues/54#issuecomment-389666169).
> 
> > Additionally, allowing model properties to be read from stream would also be greatly beneficial.
> 
> I don't think that Scriban should provide such a built-in thing, as it is very app specific (another person could start to come with e.g "I want to read properties from a socket or a pipe or a database..."). That being said, a scripting object in Scriban is abstracted via the interface [`IScriptObject`](https://github.com/scriban/scriban/blob/master/src/Scriban/Runtime/IScriptObject.cs), so you could develop an implementation that fits exactly what you are looking for.

Thanks - I can successfully output to stream without a problem!

Re: the IScriptObject interface - If I understand correctly, the output of any rendering is a string, which would mean that any stream implementation would need to be loaded into memory as string entirely before it is written back out using PopOutput?
I guess this is by-design, unless there's some other way that I can't see?

**Comment by xoofx** [comment]
> Re: the IScriptObject interface - If I understand correctly, the output of any rendering is a string, which would mean that any stream implementation would need to be loaded into memory as string entirely before it is written back out using PopOutput?
I guess this is by-design, unless there's some other way that I can't see?

The Scriban runtime is using a kind of stdout (the `TemplateContext.PushOutput`) but nothing stops you to "render" or output e.g binary data to a file if you want. You can bind anykind of functions and put your "output" to other place. If I was making a // with C#, you are not forced to use `Console.WriteLine` either.

Otherwise, related to `IScriptObject` I'm not sure to understand the link to the rendering and your question (there is an unclear mix of what is the input and output, not sure which one you are referring to). A IScriptObject is a dictionary<string, object>, it doesn't render or force to output strings in any way, so I assume it's your input and you can also do whatever you want here (e.g expose a byte[] if you want)

**Comment by Jasonkingsmill** [comment]
Thanks, I thought I should follow up.
I've got support for large input Streams working by using a custom TemplateContext, overriding the Write method of the context - also using PushOutput(<textwriter>) 

```
public override TemplateContext Write(SourceSpan span, object textAsObject)
{
    if (textAsObject is Stream)
    {
        using var reader = new StreamReader(textAsObject as Stream, leaveOpen: true);
        while (!reader.EndOfStream)
        {
            char[] buffer = new char[StreamReadBufferSize];
            while (!reader.EndOfStream)
            {
                int bytesRead = reader.ReadBlock(buffer, 0, buffer.Length);
                ArraySegment<char> outChars = new ArraySegment<char>(buffer, 0, bytesRead);
                base.Write(new string(outChars), 0, outChars.Length);
            }
        }
        return this;
    }
    else
    {
        var text = base.ObjectToString(textAsObject);
        base.Write(text, 0, text.Length);
    }

    return this;
}
```
