### ISSUE TITLE
Variable name with spaces

### ISSUE THREAD

**Issue by besmiralia** [scriban/scriban#448]
How can I configure a variable that has a space character in it's name?
Something like this
`{{ table name.field name}}`

**Comment by xoofx** [comment]
`{{ table name["field name"] }}`

**Comment by besmiralia** [comment]
@xoofx thank you for your response. From this, I assume the `table name` can accept spaces?
Maybe this example would clarify more of my questions. If we had a variable like below, would this be the right syntax?

`{{ table name["sub table name"]["field name"]`

**Comment by xoofx** [comment]
`{{ this["table name"]["sub table name"]["field name"] }}`

**Comment by besmiralia** [comment]
Thank you so much
