### ISSUE TITLE
Feature Request: case insensitive name resolver in TypedObjectAccessor

### ISSUE THREAD

**Issue by kae** [scriban/scriban#449]
Add setting in TemplateContext (analogues to https://github.com/scriban/scriban/blob/master/src/Scriban/Runtime/ScriptObject.cs#L42 ) to create TypedObjectAccessor with it ( https://github.com/scriban/scriban/blob/master/src/Scriban/TemplateContext.cs#L898 )

So name resolution be consistent within levels of object hierarchy.

**Comment by xoofx** [comment]
That's the purpose of `TemplateContext.MemberRenamer`:

https://github.com/scriban/scriban/blob/b849c549eed423eb2a3e111b759ae8a256aaee60/src/Scriban/TemplateContext.cs#L245-L248

**Comment by kae** [comment]
I don't understand how renamer can provide case insensitivity.

If template contains both reference "{{ VAR }}" and "{{ var }}"

**Comment by xoofx** [comment]
> I don't understand how renamer can provide case insensitivity.

oh, sorry, misunderstood. Indeed, it is not possible. PR welcome.

**Comment by kae** [comment]
@xoofx 

Has local implementation, but not sure should I add some test cases for it.
And if it's needed than where it should be.

**Comment by xoofx** [comment]
> Has local implementation, but not sure should I add some test cases for it.
> And if it's needed than where it should be.

In [TestRuntime.cs](https://github.com/scriban/scriban/blob/master/src/Scriban.Tests/TestRuntime.cs)
