### ISSUE TITLE
Is there a utility for outputting a model's schema?

### ISSUE THREAD

**Issue by Joebeazelman** [scriban/scriban#454]
I can't run any of the Scriban editors or IDEs on my Mac. Consequently, I am locked out of three essential productivity features: autocomplete, syntax coloring and live preview.  

I am getting around it by writing a scaffolding app with previewing capabilities through dotnetcore's watch facility.  It will process and reload my templates in VSCode whenever it detects a change in any of them. I will at least get syntax coloring by using the Scriban extension, but it won't help with autocomplete.  

Is there a function in Scriban or a utility for dumping out a model's structure and members? Without autocomplete, it is a real pain to target the correct element of a model. In my case, I am converting from XML to POCO and then to Scriban. Such a feature would autocomplete trivial to implement.

**Comment by xoofx** [comment]
The model is what you put in the `IScriptObject` accessible in the stack of objects pushed via the `TemplateContext.PushGlobal`. So inspecting the model should not be more complicated than iterating the `IScriptObject` members as you would do for a `Dictionary<string, object>`.
But beware that Scriban is a dynamic language that is not statically typed, so the model is dynamic and could be changed at any point in a program (e.g by a certain function that changes the underlying models)
