### ISSUE TITLE
Question: Can a script specify what parameters it requires (or other meta-data)?

### ISSUE THREAD

**Issue by mrpmorris** [scriban/scriban#456]
I am creating a Roslyn code generator.  At the moment I am using T4 but want to migrate away.  

https://youtu.be/hP59npROrJo

I find all scripts and then parse them, and for each script I find I then create an Attribute.  One thing I find useful in T4 is that I can have the script tell me what input it expects.

So, given a script called `Repeat.tt` I can do this
```
<#@ parameter type="System.Int32" name="TimesToRepeat" #>
```

And then generate an attribute like this

```
public class RepeatAttribute : Attribute
{
  public int TimesToRepeat { get; set; }
}
```

To achieve this I must let the developer do the following
1. Create a script
2. (Code-gen creates an Attribute per script)
3. Decorate their classes with the attributes auto generated from those scripts
4. (Code-gen executes the script along with the inputs from the Attribute to generate additional code for this class)

The important thing is, the input names + types can be determined at the time the template is parsed rather than when it is executed.  

So, the question is.

Is there a way I can do the equivalent with Scriban?  Have the script some how define information I can extract after parsing, but that doesn't get executed when the script is run?

**Comment by xoofx** [comment]
> Is there a way I can do the equivalent with Scriban? Have the script some how define information I can extract after parsing, but that doesn't get executed when the script is run?

Nothing builtin, but the way to do it is to take your own convention on how to define such constraints and parse the document accordingly. For example, in [lunet](https://github.com/lunet-io/lunet) it is parsing a YAML or Scriban frontmatter (delimited by `---`) and the rest of the document is parsed as pure Scriban:

```
---
TimesToRepeat: System.Int32
---
Content of your template here...
```

**Comment by mrpmorris** [comment]
Thank you for your quick response!

And thanks again for your scripting engine!!
