### ISSUE TITLE
Is the generated code for templates garbage collected?

### ISSUE THREAD

**Issue by mrpmorris** [scriban/scriban#458]
Once an instance of Template is garbage collected, is the generated code also released?

I am going to be compiling templates, using, then allowing them to be collected and would like to know if this pattern will leak memory?

**Comment by xoofx** [comment]
> Once an instance of Template is garbage collected, is the generated code also released?

There is no generated code, the AST is going through an interpreter, so there should be no leak (also, no static in Scriban for such things)

**Comment by mrpmorris** [comment]
Oh, I thought it converted it to IL.

Thank you again!
