### ISSUE TITLE
Minus at the beginning of a line not evaluated properly?（5.5.0）

### ISSUE THREAD

**Issue by so-suzuki-kke** [scriban/scriban#459]
This time it works as expected.
{{ x - 10  }}  

In this case, it doesn't work as expected and I think it will be 10+x.
{{ - 10 + x  }}  

Is this a specification constraint?

**Comment by xoofx** [comment]
This is working as expected, so you might have a different case:

```
[Test]
public void Test()
{
    var input = @"{{ -10 + x }}";
    var template = Template.Parse(input);
    var result = template.Render(new { x = 30 });
    Assert.AreEqual("20", result);
}
```

Could you post a complete code as I did above that demonstrates that it is not working as expected?
