### ISSUE TITLE
"Unable to convert type 'string' to int" when using JObject with string indexer

### ISSUE THREAD

**Issue by joao-sgoncalves** [scriban/scriban#460]
Hi,

I am trying to use Scriban to parse and render a template using a dynamically desserialized JSON as the model (with NewtonsoftJson). I initially receive an XML string, which I parse and serialize to a JSON string, so that I can then desserialize that JSON string into a dynamic object, to access its properties in the template. I have been doing this with NewtonsoftJson and Scriban without any problems, all works. But now, as I am working with XML, Newtonsoft creates JSON strings that have properties with symbols like '@' prepended, which result in invalid C# variables. To overcome this, I am accessing those specific properties using string indexer, like this:

```csharp
using Newtonsoft.Json;
using Scriban;
using System.Xml.Linq;

// Parses the specified XML and serializes it to JSON.
string xml = "<Person Id=\"1\" FirstName=\"John\" LastName=\"Doe\" />";
var document = XDocument.Parse(xml);
string json = JsonConvert.SerializeXNode(document);

// Desserializes JSON into dynamic object.
dynamic response = JsonConvert.DeserializeObject(json);
Type responseType = response.GetType();

string personId = response.Person["@Id"]; // response.Person.@Id would be invalid!
string personFirstName = response.Person["@FirstName"];
string personLastName = response.Person["@LastName"];
            
// Parses the specified text into a template.
string text = "Id: {{ Response.Person[\"@Id\"] }}; FirstName: {{ Response.Person[\"@FirstName\"] }}; LastName: {{ Response.Person[\"@LastName\"] }}";
var template = Template.Parse(text);

// Renders the template using the specified model.
string result = await template.RenderAsync(new { Response = response }, member => member.Name);
```

When I try to access the properties outside the template, everything works, and their values are correctly obtained from response.
But when I do the same inside the template, I get the error "Unable to convert type 'string' to int". Am I missing something here?

Thanks for your help

**Comment by xoofx** [comment]
Scriban doesn't support dynamic, so you should probably not use it. Deserialize your JSON to a properly `Dictionary<string, object>`. I believe Newtonsof.Json should support such deserialization. If it doesn't you might have to create a small helper to deserialize to a dictionary directly (it is just a couple of lines like [this](https://github.com/lunet-io/lunet/blob/54ed2989f92883d925f89b04f36366c229896fba/src/Lunet.Json/JsonUtil.cs#L62-L119))

**Comment by joao-sgoncalves** [comment]
Can you clarify on "Scriban doesn't support dynamic"? I have been using this and it works like a charm:

```csharp
string otherJson = "{ \"Person\": { \"Id\": 1, \"FirstName\": \"John\", \"LastName\": \"Doe\" } }";
dynamic otherResponse = JsonConvert.DeserializeObject(otherJson);

string otherPersonId = otherResponse.Person.Id;
string otherPersonFirstName = otherResponse.Person.FirstName;
string otherPersonLastName = otherResponse.Person.LastName;

// Parses the specified text into a template.
string otherText = "Id: {{ OtherResponse.Person.Id }}; FirstName: {{ OtherResponse.Person.FirstName }}; LastName: {{ OtherResponse.Person.LastName }}";
var otherTemplate = Template.Parse(otherText);

// Renders the template using the specified model.
string otherResult = await otherTemplate.RenderAsync(new { OtherResponse = otherResponse }, member => member.Name);
```

**Comment by xoofx** [comment]
Sorry, I took a shortcut, I meant the string indexer with dynamic. I don't know if it can be fixed, personally no time or interest to fix this case, so if you feel brave to try, PR welcome

**Comment by joao-sgoncalves** [comment]
Ok, got it. I'll give your solution a try, or check if string indexing can be easily be added. Thanks for the help
