### ISSUE TITLE
Can't able to use Scriban reference dll in WPF Application (.NET Framework)

### ISSUE THREAD

**Issue by Sadhiq6** [scriban/scriban#461]
#I am using Scriban reference dll of version 5.5.0. I am trying to add this reference file in my WPF application or XAML file used application while adding it shows error in the XAML file InitializeComponent() as [Error CS0103 The name 'InitializeComponent' does not exist in the current context]

![image](https://user-images.githubusercontent.com/106057140/192461099-6f067f85-f187-46bd-a77d-d53e84a22cdd.png)

**Comment by xoofx** [comment]
Sorry, but this error doesn't help to explain why Scriban would be responsible for it, so it is unlikely Scriban in itself (it is a library that has no knowledge of WPF or XAML). There is a misusage somewhere else in your project generating such error.
