### ISSUE TITLE
Possibility to declare an anonymous function in a variable initializer

### ISSUE THREAD

**Issue by cvanherk** [scriban/scriban#466]
Hi xoofx.

While developing, I stumbled on a problem.
I encountered a situation, that with a include statement, I could override a defined function with the same name, as loaded by the include statement.
That situation may be valid and logical, but it is something I would want to prevent.
I tried to declare a function like this:

```scriban
{{
   some_variable = {
      test_func: do
         ret '1'	
      end,
      another_func: do
         ret '2'
      end
   }
}}
```
However, this is not valid. It would be very nice if this could be possible.
Is there a way to declare anonymous functions like this?

Thanks in advance.

**Comment by xoofx** [comment]
You can probably use a different syntax like this:

```
{{
   some_variable = {}
   with some_variable
     func test_func
        ret '1'	
     end
     func another_func
        ret '2'
     end
   end
}}
```

**Comment by cvanherk** [comment]
Thanks, this is what I was looking for!
