### ISSUE TITLE
Template - list of interpolated variables in a template

### ISSUE THREAD

**Issue by co-dax** [scriban/scriban#467]
Is it possible to get a list of interpolated variables in a template?

Just for clarity, by "interpolated variables" I am referring to "name" in the following line of code
`var template = Template.Parse("Hello {{name}}!");`

I need this as I am dynamically loading templates from the database so I need validate if the template needs any varible to be rendered properly.

Thanks!

**Comment by xoofx** [comment]
Similar to #465

**Comment by xoofx** [comment]
> How does one differentiate variables expected to be provided to evaluation? 

That would be significantly more involving in the `ScriptVisitor`, as you would have to build an entire variable control flow to detect this (e.g which one are assigned before being read/write).
It's doable but quite some work. That would also not cover dynamic cases (e.g `this[indirect_variable]= 1` where `indirect_variable` is a dynamically string e.g `product`)

**Comment by stephentoub** [comment]
Thanks. If I was willing to scale it back heuristically to just look for variables never explicitly assigned, where should I be looking in the object model? Is there a sample somewhere?

**Comment by xoofx** [comment]
> Thanks. If I was willing to scale it back heuristically to just look for variables never explicitly assigned, where should I be looking in the object model? Is there a sample somewhere?

That part was introduced recently but I never had the time to document this part unfortunately.

The visitor is fairly easy to follow:

https://github.com/scriban/scriban/blob/38df14946721238d2f4badc7c0b6e8a1c594e23c/src/Scriban/ScribanVisitors.generated.cs#L1443-L1495

Similarly, the AST should be easy to follow as well (e.g detecting `ScriptAssignExpression`). But you would need to detect the other implicit assignments (the `product` variable in the `for product in products`)

If you use some of the sample above to dump the syntax tree, with a few examples, you should be able to see how the AST is built for the different cases.

**Comment by stephentoub** [comment]
Thanks :)
