### ISSUE TITLE
Possible to prevent object.eval from producing output?

### ISSUE THREAD

**Issue by allsorts46** [scriban/scriban#470]
Hello, I've been trying to parse a hex string provided as a variable from the runtime host into an integer, so I can do further math operations on it. 

I first tried using string.to_int, but this doesn't seem to understand hex literals. Assuming myhex is a string "FF":

```
v = string.to_int ('0x' + myhex)
v
```

unfortunately produces nothing.

I then came across object.eval, and tried:

```
v = object.eval ('0x' + myhex)
v
```

This appeared to work and output '255', however when I tried to take this example further and do some operations, I discovered that the '255' is actually being produced on the first line not the second line, and 'v' has no value.

```
v = object.eval('0x' + myhex) / 255f
```

therefore still outputs '255', because object.eval produces '255' directly to output and the division does nothing at all.

I understood from the documentation that assignment expressions do not produce output, but object.eval seems to be an exception from this.

I've worked around the problem for now by importing a .NET HexToDec function via the runtime host, but would like to be able to achieve this purely in scriban if possible.

Thanks!

**Comment by xoofx** [comment]
Indeed, `object.eval` should return the value instead of rendering. It should be fixed by commit 
ee1f66d and will be published soon in a `5.5.1+`
