### ISSUE TITLE
Case statement failing

### ISSUE THREAD

**Issue by andyb70** [scriban/scriban#471]
I'm using v5.5.1

I'm attempting to parse the case statement used in the documentation with the following template:

````
{{
x = 5
case x
    when 1, 2, 3
        "Value is 1 or 2 or 3"
    when 5
        "Value is 5"
    else
        "Value is " + x
end
}}
````

but the parser is raising the following exception:

````
This template has errors. Check the <Template.HasError> and <Template.Messages> before evaluating a template. Messages:
<input>(1,24) : error : Invalid token found `,`. Expecting <EOL>/end of line.
````

So I then tried the following template:
````
{{
x = 3
case x
    when 0
        "Value is 0"
    when 1
        "Value is 1"
    when 2
        "Value is 4"
    when 3
        "Value is 3"
end
}}
````
and now I get the following error:
````
<input>(1,7) : error : Invalid target function `3` (int)
````
I'm at a loss as to how to implement the case/when statement in my template?

**Comment by xoofx** [comment]
Could you show the full code of parsing, initializing and running the template in a small code snippet?

**Comment by andyb70** [comment]
I've extracted the template into a code snippet and it works OK, however if change the template to put {{ }} around all statements it works fine so there must be something else that is causing the problem which is unique to our setup.
