### ISSUE TITLE
Negative numbers as function arguments

### ISSUE THREAD

**Issue by Vanglant** [scriban/scriban#472]
Hi! While running some Scriban scripts we have found a couple of runtime errors when using negative numbers as function parameters: 

`{{ date.now | date.add_days -1 }}` -> `Scriban.Syntax.ScriptRuntimeException : <input>(1,28) : error : Invalid number of arguments 1 passed to date.add_days while expecting 2 arguments`.   

`{{ 200 | math.minus -1}}` same result

Also in Liquid: `{{ 200 | minus: -1}}`

So far I have managed to find a workaround assigning `-1` to a variable (in Liquid):

```text
{% assign test = -1 %}
{% assign date_test = date.now | date.add_days test  %}
{{ date_test }}
```

The issue seems to be that `-1` is not considered an argument, is this intended behavior somehow? Or maybe not implemented? 
Thank you!!

**Comment by xoofx** [comment]
Yes, it is a restriction with the parentless function call that makes it difficult to distinguish from a binary operation. So if you put the negative number in parenthesis, that should work `{{ date.now | date.add_days (-1) }}`
