### ISSUE TITLE
Functions and calculations not working

### ISSUE THREAD

**Issue by kavatari** [scriban/scriban#475]
Hi all, 

can anyone help on this one please... Calculations do not work and are not parsed... 

**Examples:** 
{{ (price - close) / close * 100 }} => empty string, no exceptions.

**Define function:** 
{{func relative(price,close) 
    ret ((price-close)/close*100)
end}}
_call it like:_ {{ relative | price close }} => not working no output. Calling the funciton with only one argument throws an exception. 

What is wrong here?

**Comment by xoofx** [comment]
It would be easier if you could post a fully working small `Program.cs` that demonstrates how you instantiate this template, what is your model, how do you interact with the library...
