### ISSUE TITLE
Feature request: string interpolation

### ISSUE THREAD

**Issue by ranger-turtle** [scriban/scriban#476]
Most modern languages have string interpolation i.e. possibility to put the expressions into string **without** use of concatenation.
Interpolated strings look like this in C#: `$"Number: {number + 3}"`
Would it be possible to add this kind of syntactic sugar?

**Comment by xoofx** [comment]
Agreed. Don't have personal time to implement this. I did it for another project and It's not completely trivial as it requires to change the lexer, but it is doable. PR welcome if someone is brave!

**Comment by ranger-turtle** [comment]
I consider implementing interpolated string support.
But I do not know what kind of implementation would you accept.
I would like to make the interpolation syntax like `"Count: #{2 + 4}."` to be compatible with Ruby language. However, it can be used on literals with double quotes only on this language. And if you want to preserve such compatibility with Ruby, I need to make separate type of string token I would call `InterpolatedString`, and regular `String` token type would support single-quoted literals only since then. When I implement interpolation for both types of regular strings, Scriban language will be less compatible with Ruby.
What do you think?

**Comment by ranger-turtle** [comment]
Mr @xoofx , I consider implementing interpolated string support.
But I do not know what kind of implementation would you accept.
I would like to make the interpolation syntax like "Count: #{2 + 4}." to be compatible with Ruby language. However, it can be used on literals with double quotes only on this language. And if you want to preserve such compatibility with Ruby, I need to make separate type of string token I would call InterpolatedString, and regular String token type would support single-quoted literals only since then. When I implement interpolation for both types of regular strings, Scriban language will be less compatible with Ruby.
What do you think?

**Comment by xoofx** [comment]
> I would like to make the interpolation syntax like "Count: #{2 + 4}."

The syntax will most likely require a prefix before the `"` to avoid breaking existing code (but also you really want to have the lexer start the parsing from the first `"`). I believe that using the prefix `$` like `$"..."` would be a more natural syntax (Example: `$"This is a string with a variable {$a}"`)

**Comment by ranger-turtle** [comment]
Merci, but I would like to know if I can apply to both of the delimiters.

**Comment by xoofx** [comment]
> Merci, but I would like to know if I can apply to both of the delimiters.

I'm not sure to follow, could you give an example?

**Comment by ranger-turtle** [comment]
"Interpolation: #{2 + 4}"
'Interpolation: #{2 + 4}'

**Comment by xoofx** [comment]
Do you mean between `"` and `'`, if that's the question, yes definitely. Otherwise, the syntax should be similar to C# string interpolation as in the example `$"This is a string with a variable {$a}"`. Don't want to introduce a Ruby syntax here.

**Comment by xoofx** [comment]
> because it's based on Ruby

I'm confused, where have you read that it is based on Ruby?

**Comment by ranger-turtle** [comment]
I have found out myself. Besides, Liquid template uses Ruby-based language and is written in Ruby itself.
I know Scriban does not need to be fully compatible with Ruby language, that is why I wanted to ask you. I will make $-leading interpolating strings then.

**Comment by ranger-turtle** [comment]
I have begun writing interpolation and because of the printers used in e.g. `ScriptLiteral` class, I consider making three kinds of string tokens: BeginInterpolationStringToken ("string), MiddleInterpolationStringToken (string without delimiters and EndInterpolationStringToken (string")).
What do you think?

**Comment by xoofx** [comment]
> I know Scriban does not need to be fully compatible with Ruby language, that is why I wanted to ask you. I will make $-leading interpolating strings then.

Scriban was really not developed with Ruby in mind. 🙂  It was not even develop at the beginning with a compatibility mode for parsing Liquid. It was inspired by many text languages, and Liquid was not the primary inspiration (but Liquid was the primary source of frustration, because of Jekyll templating on GitHub)

> I consider making three kinds of string tokens [...] What do you think about it?

I haven't thought about it, but I would think that you might need to add 3 tokens:
- A Begin Interpol String `$"xxxxxxx{`
- A End Interpol String `}xxxxxx"`
- A Continuation Interpol String `}xxxxxx{`
- A classic String `$"xxxxxx"` (the leading `$` is in the end not use)

**Comment by ranger-turtle** [comment]
> Scriban was really not developed with Ruby in mind. 🙂 It was not even develop at the beginning with a compatibility mode for parsing Liquid. It was inspired by many text languages, and Liquid was not the primary inspiration (but Liquid was the primary source of frustration, because of Jekyll templating on GitHub)
I see. 🙂
> I haven't thought about it, but I would think that you might need to add 3 tokens
That is what I am talking about. Merci for your answers, including `$` discarding.

**Comment by ranger-turtle** [comment]
I have finished my attempt to add string interpolation. However, I have noticed you have tests that check if everything works. I have added some of ones checking if interpolation works to a new folder `TestFiles/020-interpolation`. May I make a pull request? You would check if the interpolation is not too unstable and what tests should I add and where.

**Comment by xoofx** [comment]
> May I make a pull request? 

Sure.
