### ISSUE TITLE
JSON to JSON transformation for json object value

### ISSUE THREAD

**Issue by joshidp** [scriban/scriban#480]
Hello,

I am using liquid templates for JSON to JSON transformations.  I am facing issue while setting json object as value, insted of setting json object scriban is converting json object to key value and setting it as value.

**Input**
```

{
  "data": {
    "skuService": {
      "nodes": [
        {
          "sKUNumber": "AAAAAAA-01",
          "type": "Base",
          "sKUDescription": "Pro 10-Pack",
          "phxService": {
            "name": "- 10 Pack",
            "partNumber": "AAF-000",
            "itemCode": "SPPL",
            "itemId": 1978,
            "itemType": {
              "itemTypeCode": "SVAC"
            },
            "serviceType": {
              "id": 22,
              "code": "XXX",
              "value": "Problem Support"
            },
            "serviceFamily": {
              "id": 4,
              "code": "REA",
              "value": "Reactive",
              "serviceCategory": {
                "id": 6,
                "code": "QQQ",
                "value": "Reactive"
              }
            }
          }
        }
      ]
    }
  }
}
```

**Liquid Template**
```
[

{{- for node in model.data.skuService.nodes}}
{"offeringAttributes": {
"servicePartNumber": "{{ node.sKUNumber}}",
"itemId":{{ node.phxService.itemId}},
"itemCode": "{{ node.phxService.itemCode}}",
"itemName": "{{ node.phxService.itemType.itemTypeCode}}",
"itemTypeCode": "{{ node.phxService.itemType.itemTypeCode}}",
"serviceType": {{ node.phxService.serviceType}},
"serviceFamily": {{ node.phxService.serviceFamily}},
}
{{if !for.last; '},'; ''; end}}
{{- end }}
}

]
```

**Actual Output**

```
[
  {
    "offeringAttributes": {
      "servicePartNumber": "AAAAAAA-01",
      "itemId": "1978",
      "itemCode": "SPPL",
      "itemName": "SVC",
      "itemTypeCode": "",
      **"serviceType": "[{key: "id", value: 22}, {key: "code", value: "PSU"}, {key: "value", value: "Problem Resolution Support"}]",
      "serviceFamily": "[{key: "id", value: 4}, {key: "code", value: "REA"}, {key: "value", value: "Reactive"}, {key: "serviceCategory", value: [{key: "id", value: 6}, {key: "code", value: "REA"}, {key: "value", value: "Reactive"}]}]",**
    }
  }
  }
]
```

**Expected Output**

```
[
{
			"offeringAttributes": {
				"servicePartNumber": "AAF-07865",
				"itemId": 1978,
				"itemCode": "SPPL",
				"itemName": "Problem Resolution Hours - 10 Pack",
				"itemTypeCode": "SVC",
				"serviceType": {
					"id": 22,
					"code": "PSU",
					"value": "Problem Resolution Support"
				},
				"serviceFamily": {
					"id": 4,
					"code": "REA",
					"value": "Reactive",
					"serviceCategory": {
						"id": 6,
						"code": "REA",
						"value": "Reactive"
					}
				}
			},
			"skuAttributes": {
				"number": "#ABC-01",
				"type": "Base",
				"sKUDescription": "Problem Resolution Hours 10-Pack"
			}
		}
]
```

Please suggest how json object can be set as value as it is.

Thanks!

**Comment by xoofx** [comment]
How do you load the JSON input? There is no built-in support for JSON output (couldn't take a dependency on an external library), so you would have to create a small function to provide an exact JSON output.

**Comment by joshidp** [comment]
> How do you load the JSON input? There is no built-in support for JSON output (couldn't take a dependency on an external library), so you would have to create a small function to provide an exact JSON output.

Using below code snippet.


      ```
      var json = File.ReadAllText("Input.json");
            var template = Template.Parse(File.ReadAllText("liquid.liquid"));
            var result = template.Render(new { model = JsonConvert.DeserializeObject<ExpandoObject>(json) });
```

**Comment by xoofx** [comment]
`ExpandoObject` are unlikely to work correctly in that case but also, no matter what, my suggestion stand that in order to output correct formatted JSON, you should implement a helper method. Scriban doesn't provide any input/output built-in JSON support.

**Comment by joshidp** [comment]
> `ExpandoObject` are unlikely to work correctly in that case but also, no matter what, my suggestion stand that in order to output correct formatted JSON, you should implement a helper method. Scriban doesn't provide any input/output built-in JSON support.

Helper method you are suggesting to handle nested property JObject handling or for entire JSON to JSON transformation, because transformation using scriban template is working fine, its just the nested objects which needs to be handled.

Also, how do we register a method in below question similar issue is asked and you have suggested to register the function to handle json conversation.

[to_json](https://github.com/scriban/scriban/issues/85)

**Comment by xoofx** [comment]
> because transformation using scriban template is working fine, its just the nested objects which needs to be handled.

That's not completely true. "Working fine" can be also by accident. When there is a line like `"itemCode": "{{ node.phxService.itemCode}}",` if item code has a `"` it would not be escaped as it should in a properly formatted JSON output. If you need to protect your output also from tampering/injection, this is not safe.

> Also, how do we register a method in below question similar issue is asked and you have suggested to register the function to handle json conversation.

In the [doc](https://github.com/scriban/scriban/blob/master/doc/runtime.md#imports-functions-from-a-net-class) and just below.

**Comment by joshidp** [comment]
> > because transformation using scriban template is working fine, its just the nested objects which needs to be handled.
> 
> That's not completely true. "Working fine" can be also by accident. When there is a line like `"itemCode": "{{ node.phxService.itemCode}}",` if item code has a `"` it would not be escaped as it should in a properly formatted JSON output. If you need to protect your output also from tampering/injection, this is not safe.
> 
> > Also, how do we register a method in below question similar issue is asked and you have suggested to register the function to handle json conversation.
> 
> In the [doc here](https://github.com/scriban/scriban/blob/master/doc/runtime.md#imports-functions-from-a-net-class) and just below.

OK, I thought JSON to JSON transformation would become easier with Liquid but that's not the case. If you know any good lib/nuget for JSON to JSON transformation please do share.

Thanks!

**Comment by joshidp** [comment]
I think proper solution for this issue is to implement https://shopify.dev/api/liquid/filters/json , currently its not working.

**Comment by xoofx** [comment]
> I think proper solution for this issue is to implement https://shopify.dev/api/liquid/filters/json , currently its not working.

Right, and it is one helper `to_json` method away. It's not like it's going to require weeks of dev. It is just requiring to use an existing JSON framework and transform e.g ScriptObject to it. 

Today, Scriban can't have any dependencies on JSON because it would require e.g a new version of .NET (e.g 6.0+ at least) or to have a dependency to a NuGet library. That's why it's not built-in. But writing a bridge is really not much work. 

For example, I wrote a simple function to convert JSON to Scriban ScriptObject [here](https://github.com/lunet-io/lunet/blob/54ed2989f92883d925f89b04f36366c229896fba/src/Lunet.Json/JsonUtil.cs#L62-L119). The opposite can be done also easily.
