### ISSUE TITLE
Distinct array from nested data model

### ISSUE THREAD

**Issue by joshidp** [scriban/scriban#481]
How can use get distinct array out of data e.g. ["Bahamas", "USA"] for below data. I tried assign in for loop but its not giving desired result.

[{{- for req in reqs}} {{req.nestedObj.country}}  {{if !for.last; ','; ''; end}}{{- end }}]

**Data**
`[
  {
    "dob": "2022-11-11T00:00:00",    
    "nestedObj": {
         "country": "Bahamas"
    }
    },
{
    "dob": "2022-11-11T00:00:00",    
    "nestedObj": {
         "country": "USA"
    }
    },
  {
    "dob": "2022-11-11T00:00:00",
    "nestedObj": {
      "country": "USA"
    }
  }
]`

**Comment by joshidp** [comment]
Basically, if I can pass the for loop output to a custom function then it can be achieved, I am able to get ["Bahamas", "Bahamas", "USA"] from the loop but not sure how to do unique operation on the output.

**Comment by binarycow** [comment]
```
{{ reqs | array.map "nestedObj" | array.map "country" | array.uniq }}
```

**Comment by joshidp** [comment]
Thanks!
