### ISSUE TITLE
How to escape a handlebar?

### ISSUE THREAD

**Issue by modmoto** [scriban/scriban#485]
I have issues rendering this string latex here

```
\textbf{{{ Name }}} 
```

I was expecting this output:

```
\textbf{ Simon } 
```
when I pass in an object where property `Name = Simon`, but I get an exception when parsing the template that `{` is an invalid character at the given point.

So far I tried the following combinations to no avail.

```
\textbf{{"\{Name\}"}}
\textbf{{\{Name\}}}
\textbf\{{{Name}}\}
\textbf{%{{}%}{{Name}}{%{}}%}
\textbf{{{%{{}%}Name{%{}}%}}}
\textbf{%{{{Name}}%}
```

Is this even possible and if so how? I did not find any the documentation that mentions how to escape the `{` character.

**Comment by xoofx** [comment]
Couldn't you write `\textbf{ {{ Name }} }` instead? (You need at least 1 space before the `{{` and after `}}`)

**Comment by modmoto** [comment]
Oh boy, yeah that fixed it xD I was not aware that spaces would make a difference. Thanks!
