### ISSUE TITLE
scriptobject.import renamer does not seem to be renaming when key contains ":"  

### ISSUE THREAD

**Issue by msterin** [scriban/scriban#486]
I am trying to import into a ScriptObject a dictionary with "xxx:yyy" keys. I need to strip 'xxx:' part from the keys. 
renamer seems to ignore the stripping: `renamer: m => m.Name.Split(':')[1]);`

Not sure if I am doing something wrong or this is just a bug, but running this:

```c#
var so = new ScriptObject();

so.Import(new Dictionary<string, object> {
   {"test:one", 1},   {"test:two", 2},
}, renamer: m => m.Name.Split(':')[1]);

foreach (KeyValuePair<string, object> kvp in so) {
   Console.WriteLine($"key={kvp.Key} value={kvp.Value}");
}
```

Produces this: 

```txt
key=test:one value=1
key=test:two value=2
```

When I expected 
```
key=one value=1
key=two value=2
```

**Comment by xoofx** [comment]
That's by design. The renamer is only valid for objects via reflection. Otherwise in your case, better filtering the dictionary upfront. Changing this would be a breaking change unfortunately.

**Comment by msterin** [comment]
That for swift reply, and understood - still would be nice to mention it in the docs...
