### ISSUE TITLE
RS1035 error for Environment.NewLine

### ISSUE THREAD

**Issue by chunliu** [scriban/scriban#487]
This line of code triggers RS1035 when Scriban is used in a source generator and `<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>` is on to satisfy RS1036.  https://github.com/scriban/scriban/blob/85b2aabe55807eb1fa633628a20d6e525027f2a0/src/Scriban/TemplateContext.cs#L154 

Also see this issue for details: https://github.com/dotnet/roslyn-analyzers/issues/6467

**Comment by xoofx** [comment]
Tried to fix it via fb4386d, not sure if it will be enough, let's see
