### ISSUE TITLE
Fix documentation of the parameters for the 'for' statement

### ISSUE THREAD

**Issue by artur-simon** [scriban/scriban#490]
The examples in the documentation do not seem to check out

Example 1 (not working): 

```
{{ 
    for i in 1..5 reversed
        i
    end 
}}
```

This gives us: `error : Invalid target function '5' (int)`

Example 2 (what actually worked):
```
{{ 
    for i in 1..5 | array.reversed
        i
    end 
}}
```

This gives us: `5 4 3 2 1` as expected.

This is the same for the `limit` and the `offset` parameters.

Tried it over the playground and it checks out.

https://scribanonline.azurewebsites.net/

Created a pull request to adress this correction at #489.

**Comment by xoofx** [comment]
Thanks for spotting this! So actually, it requires parenthesis, fixed by #489 

```
{{ 
    for i in (1..5) reversed
        i
    end 
}}
```
