### ISSUE TITLE
Cannot get the member regex.split for a null object

### ISSUE THREAD

**Issue by mrpmorris** [scriban/scriban#492]
I'm writing this - https://github.com/mrpmorris/Morris.Moxy

In the branch `OtherTargets` I have added a call to `regex.split`

https://github.com/mrpmorris/Morris.Moxy/blob/OtherTargets/Source/Tutorials/02-MixInArguments/MixinArguments/Mixins/CountDown.mixin

But when I execute the script (i.e. when the Roslyn compiler executes my plugin) I get the error in the title.

Have I forgotten to declare something?

Thanks!

**Comment by xoofx** [comment]
Could you point where you call the Scriban renderer? It looks like an invalid usage. Have you tried to run this outside of Roslyn with a simple unit test?

**Comment by mrpmorris** [comment]
Thanks for your quick reply!

It seems it only happens if I specify a `ScriptObject` when creating my `TemplateContext`.

```
	internal class Program
	{
		const string Script = "{{ \"a,b,c\" | regex.split(\"/\") }}";

		static void Main(string[] args)
		{
			var scribanTemplate = Template.Parse(Script);

			var scribanScriptObject = new ScriptObject {
					{ "moxy", typeof(Program) }
				};

			var scribanTemplateContext = new TemplateContext(scribanScriptObject)
			{
				MemberRenamer = m => m.Name
			};

			string result = scribanTemplate.Render(scribanTemplateContext);
			Console.WriteLine(result);
			Console.ReadLine();
		}
	}
```

**Comment by xoofx** [comment]
I see. The more correct approach is to push your model on top of the built-in (that's what is done when you do [TemplateContext.Render(object)](https://github.com/scriban/scriban/blob/8953646e0c746abc95a5b69d4edc5a4f05ec2ae4/src/Scriban/Template.cs#L211))

```c#
scribanTemplateContext.PushObject(scribanScriptObject);
```

Then it resolves things in order (try first object pushed, than second, and ultimately the builtin object).

**Comment by mrpmorris** [comment]
Thanks!
