### ISSUE TITLE
Problem with array filter

### ISSUE THREAD

**Issue by sekalek** [scriban/scriban#498]
Model
`{ "items" : [ 
{ "DocID" : 1, "total" : 4.99 }, 
{ "DocID" : 2, "total" : 3.5 } 
] }`

Temple

{{- for i in model.items | array.filter @(do; ret $.DocID == 1; end) -}}
{{ i.DocID }} / {{ i.total }}
{{ end }}

And return nothing. What's wrong?

**Comment by xoofx** [comment]
Use `$0` for the first argument instead of `$` which is the array of the arguments.

```
{{- for i in model.items | array.filter @(do; ret $0.DocID == 1; end)  -}}
{{ i.DocID }} / {{ i.total }}
{{ end }}
```
