### ISSUE TITLE
How ScriptObject is supposed to be used?

### ISSUE THREAD

**Issue by joshidp** [scriban/scriban#500]
Hello Scriabin's,

I want to understand if we can create a single instance of ScriptObject for an app lifecycle. Since it has Import method to load custom function it looks like it should be instantiated once. But then,  ScriptObject also has Add method for adding template parameter and values(which I believe should be in context somewhere) which doesn't feel like a good candidate of singleton.

Can someone please clear this confusion for me?

Thanks!

**Comment by xoofx** [comment]
> I want to understand if we can create a single instance of ScriptObject for an app lifecycle. Since it has Import method to load custom function it looks like it should be instantiated once. But then, ScriptObject also has Add method for adding template parameter and values(which I believe should be in context somewhere) which doesn't feel like a good candidate of singleton.

It depends how this `ScriptObject` is accessed. If it is part of the [stack of objects](https://github.com/scriban/scriban/blob/master/doc/runtime.md#the-stack-of-scriptobject) accessible for variable binding (pushed via `TemplateContext.PushObject`), and that you guarantee that there are no direct references to this object, then it should be safe to have a singleton. On the other hand, if you make a `ScriptObject` accessible through a variable (e.g `myModel`), then any scripts running with it could modify it, but also if you have concurrent threads, that would not be thread safe.

**Comment by joshidp** [comment]
So, in 2nd case where ScriptObject  is used via model/varibale and used by concurrent threads we should be instantiating ScriptObject every time and bind the custom method?

**Comment by xoofx** [comment]
> So, in 2nd case where ScriptObject is used via model/variable and used by concurrent threads we should be instantiating ScriptObject every time/thread and bind the custom method?

It's not different from what you would have to do if the scripting engine was in pure C# (e.g Razor). Scriban is not thread-safe by default but it also depends on multiple factors, e.g if (part of) your model is readonly or not. For example, if it is readonly, you could mark a ScriptObject readonly so that it cannot be modified.

**Comment by joshidp** [comment]
I can mark ScriptObject readonly in concurrent executions but then same ScriptObject is exposing Import/Add methods which can change underlying state from different threads.
