### ISSUE TITLE
A way to pass dynamic object as context, without it getting deconstructed 

### ISSUE THREAD

**Issue by elouise-matthews** [scriban/scriban#501]
Hello, as per the title, I am looking for a way to pass a dynamically populated object as the context to `Render`. 

After passing an `IDictionary` object to `Render/RenderAsync`, Scriban [imports it into the `scriptObject`](https://github.com/scriban/scriban/blob/3912f57327e1e14cac521fdeb9b7b00d74b0aee3/src/Scriban/Runtime/ScriptObjectExtensions.cs#L55), which it does by [iterating through the existing keys](https://github.com/scriban/scriban/blob/3912f57327e1e14cac521fdeb9b7b00d74b0aee3/src/Scriban/Runtime/ScriptObjectExtensions.cs#L118) to save all the dictionary Values into the `scriptObject`. 
So if I am to pass an IDictionary interfaced object which is designed to do some background operations (i.e. fetch values from external database) upon get-key , this functionality is lost when Scriban does it's import. 

So, is there a way to pass a dynamically populated object as the context, in a way that the original object doesn't get deconstructed? 

Here's an example of what I want to achieve, but which is not working: 
```
[Test which does not succeed]
    public void TestDynamicDictionary()
    {
        var dynamicDic = new DynamicDic2();
        var template = ScribanTemplate.Parse("this is a number: {{service.x}}");
        Assert.AreEqual("this is a number: 53", template.RenderAsync(new {service = dynamicDic})); 
    }
```
```
public class DynamicDic2 : IDictionary<string,object>
{
    // inner data storage to proxy connection to an external database.
    private Dictionary<string,object> proxyData = new(){{ "x", "53" }};

    public object this[string key]
    {
        get => proxyData[key];
        set => throw new NotImplementedException();
    }
    ...implementations of other iterface necessities...
}
```

For reference, I am able to do this quite easily with similar templating libraries such as Cottle, Jinian, or HandleBars, but for various reasons I would really good if I can do this in Scriban.

**Comment by xoofx** [comment]
Your top level object needs to be a `IScriptObject` and not a dictionary and you need to interact directly with `TemplateContext` in order to achieve this. 

You can emulate the code behind without doing the import:

https://github.com/scriban/scriban/blob/3912f57327e1e14cac521fdeb9b7b00d74b0aee3/src/Scriban/Template.cs#L200-L212

like this:

```c#
public static string Render(this Template template, IScriptObject model, MemberRenamerDelegate memberRenamer = null, MemberFilterDelegate memberFilter = null)
{
    var context = new TemplateContext();
    context.MemberRenamer = memberRenamer;
    context.MemberFilter = memberFilter;
    context.PushGlobal(model);
    return template.Render(context);
}
```
