### ISSUE TITLE
Current thread's CultureInfo is not used when doing math.format

### ISSUE THREAD

**Issue by psergei** [scriban/scriban#502]
From code I see that TemplateContext has Invariant culture set as default. Maybe it makes sense to implement possibility to use default thread's culture or override culture in more convenient way instead of doing

```var templateCtx = new Scriban.TemplateContext();
                    var scriptObject = new ScriptObject();
                    scriptObject.Import(model);
                    templateCtx.PushGlobal(scriptObject);
                    templateCtx.PushCulture(CultureInfo.CurrentCulture);
                    var parsedTpl = Scriban.Template.ParseLiquid(rateTpl);
                    var description = await parsedTpl.RenderAsync(templateCtx);

**Comment by xoofx** [comment]
In 5 years, that's the first issue coming about this, so it says that it can be left in your project as a small reusable extension/static method to handle that case.
