### ISSUE TITLE
case-insensitive comparison of string?

### ISSUE THREAD

**Issue by joshidp** [scriban/scriban#508]
How can we do case-insensitive of string? I am trying below snippet but its doing case sensitive comparison.

`{{valueA!=valueB}}`

Thanks

**Comment by ranger-turtle** [comment]
I think it's possible and reasonable to make the built-in function making case-insensitive comparison.

For now, you can use this workaround:
`"Left".downcase == "LEFT".downcase`
or
`"Left".upcase == "LEFT".upcase`

**Comment by ranger-turtle** [comment]
> How can we do case-insensitive of string?

You do not need to use workaround I have written in this thread. Builtin `string.equals_ignore_case` is added to the newest version.
