### ISSUE TITLE
string.pad_left And string.pad_right does not output expected spaces

### ISSUE THREAD

**Issue by brettwinters** [scriban/scriban#514]
Taking the two examples from the [guide](https://github.com/scriban/scriban/blob/master/doc/builtins.md#stringpad_left)

'''
hello{{ "world" | string.pad_left 10 }}
'''

Only outputs 5 spaces. 

"hello     world"

In fact it seems to subtract 5 from the specified argument. So if I specify 5 then no padding, but 6 produces one space.

Same issue for pad_right

**Comment by tibel** [comment]
There is NO issue in Scriban here.

Please have a look at:
* https://learn.microsoft.com/en-us/dotnet/api/system.string.padleft
* https://learn.microsoft.com/en-us/dotnet/api/system.string.padright

**Comment by brettwinters** [comment]
You're quite correct. Apologies I must have missed the word "total length" from the docs.
