### ISSUE TITLE
Trying to add a variable for a sub context without losing the same variable in the parent context, what the best way to do that?

### ISSUE THREAD

**Issue by ste-bel** [scriban/scriban#517]
I have a context A with some variables.  I want to create a child context B having all the same variables, overwrite some variables in B without losing the parent (A) values and after rendering, drop the child context and go back to the original values (of A).  What's the best way to do this.  PushLocal, PopLocal?

**Comment by xoofx** [comment]
> I have a context A [...] a child context B

Do you mean that you are using different `TemplateContext` instances?

There is some documentation [here](https://github.com/scriban/scriban/blob/master/doc/runtime.md#the-stack-of-scriptobject) explaining the layering of `ScriptObject` via `TemplateContext.PushGlobal`/`PopGlobal`.

**Comment by ste-bel** [comment]
No, just using one TemplateContext already filled in with variables that I want to keep but I need to iterate on something (outside of Scriban) and store variables without touching the original values.  After iterating, I want to be back to exactly what was there before.

I'll try Push/PopGlobal.  Merci.

**Comment by ste-bel** [comment]
It worked with Push/PopGlobal, thank you.
