### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [scriban/scriban#521]
Maybe You will be interested in hosting API Explorer online:
https://www.robiniadocs.com/d/scriban/api/Scriban.Functions.html

This is ready-to-go, so above link can be added to README.md for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Docs-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/scriban/api/Scriban.Functions.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Docs-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/scriban/api/Scriban.Functions.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Regards
NeuroXiq

**Comment by xoofx** [comment]
Thanks for the kind proposal but I'm not interested for multiple reasons. 🙂 

* A first one is that API documentation of Scriban is far from being complete that I would not expose it as HTML pages for now.

* A second reason is that I prefer to host my doc on my own github.io pages.

* A third reason is that I have actually developed my own static website generator [lunet](https://github.com/lunet-io/lunet) which I much prefer over docfx, and I'm already using for my blog and [kalk](https://kalk.dev/). As I haven't finished the API code generation part, I'm not using it yet for API documentation, but it will come at some point.
