### ISSUE TITLE
Support HTML encoded brackets in template

### ISSUE THREAD

**Issue by HugoSousa** [scriban/scriban#525]
I have an HTML template that includes the following:
`Please visit <a href="%7B%7BportalUrl%7D%7D">` 

As you can see, the brackets are encoded as `%7B` and `%7D` as `{` and `}` are invalid characters in URLs. The HTML template comes like this from the tool we use for localizing our emails, although we store it there using the brackets - I guess it goes through a sanitization process that encodes URLs. Scriban is not able to successfully parse the variable. If I manually decode the URL and parse the following string, then everything works again:
`Please visit <a href="{{portalUrl}}">` 

My questions is: should Scriban be able to support HTML encoded brackets? If not, is there a way I can work this around with some customization?

**Comment by xoofx** [comment]
> My questions is: should Scriban be able to support HTML encoded brackets? If not, is there a way I can work this around with some customization?

Not really. Scriban is agnostic about its usage. You need to revert the escape before processing it with Scriban (e.g with something like https://html-agility-pack.net/)
