### ISSUE TITLE
可以出一份详细的文档吗？

### ISSUE THREAD

**Issue by zhang1446802857** [scriban/scriban#526]
我想做一个生成代码的工具，我的朋友告诉我Scriban可以。
可我没用过，也没有文档可以看，只在仓库介绍上了解到怎么读取字符，怎么替换。
甚至没有说怎么创建专门的模板文件，也没有说如何保存到目录下，如果依靠File，那scriban的目的似乎体现不出来，包括解析模板，也只是通过字符在替换。
希望求解

**Comment by xoofx** [comment]
Please, translate your issue description + title in English. I don't speak Chinese.

**Comment by binarycow** [comment]
For what its worth, this is what gmail's translation gives:

Can you provide a detailed document? 

I want to make a tool to generate code, and my friend told me that Scriban can do it.
But I have never used it, and there is no documentation to read. I only learned how to read characters and how to replace them from the warehouse introduction.
It doesn't even say how to create a special template file, nor how to save it to a directory. If you rely on File, the purpose of scriban seems not to be reflected, including parsing templates, and only replacing characters.
Hope to solve

**Comment by ZUOXIANGE** [comment]
Scriban 是一个强大的模板引擎,它可以方便地将模板与数据结合起来,生成各种类别的文本输出,包括代码.文件的读写可能需要你自行实现
