### ISSUE TITLE
Scripting mode

### ISSUE THREAD

**Issue by keleutos2022** [scriban/scriban#530]
Hello, 
can you provide a small example how to run some code inside scripting mode and return a value?

It would be really helpful.

**Comment by xoofx** [comment]
https://github.com/scriban/scriban/blob/24a49853d2e7c606d50de0dec70fd7bd68b70a4f/src/Scriban.Tests/TestParser.cs#L479-L501

**Comment by xoofx** [comment]
The example above does a render, but you should be able to call [`Template.Evaluate`](https://github.com/scriban/scriban/blob/24a49853d2e7c606d50de0dec70fd7bd68b70a4f/src/Scriban/Template.cs#L130-L143) and get the actual value when the expression evaluated is an expression (and not a statement). There are others `Template.Evaluate` methods as well that can parse and return a value directly.

**Comment by keleutos2022** [comment]
Thanky you very much that was exactly what I searched. Thank you for your help and effort.
