### ISSUE TITLE
Why does this despite using greedy mode keep adding newlines after the colon?

### ISSUE THREAD

**Issue by jons-bakerhill** [scriban/scriban#531]
Why does this despite using greedy mode keep adding newlines after the colon?

`    {{- property.Name + ":" -}} {{- GetPropertyType(property) -}};`
results in
``` 
PROPERTYNAME:
IPROPERTYTYPE[];
```
`    {{- property.Name + ":" + GetPropertyType(property) -}};`
Does not add a new line

**Comment by xoofx** [comment]
Closing as I can't replicate this.
