### ISSUE TITLE
Clarify why there is a Scriban.Signed package provided

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [scriban/scriban#539]
Hi there,

just a question that arises when installing Scriban as a package. Why would I choose `Scriban.Signed` over `Scriban`? Why is there a need for a signed version? In which issue / PR was it introduced to learn more about it?

Some insight would be nice. Thanks.

So lonG

**Comment by ViRuSTriNiTy** [comment]
A reason for providing a signed package can be found in https://github.com/NeVeSpl/NTypewriter/issues/106#issuecomment-1985514928

**Comment by xoofx** [comment]
Yes, sometimes folks are looking to load such assemblies in a pluggable environment and having a signed version allows to have multiple versions.

I don't do this for all my libraries, but some of them are created like this.

**Comment by ViRuSTriNiTy** [comment]
Thanks for the clarification 👍. Issue closed.
