### ISSUE TITLE
Spacing I can't seem to figure out

### ISSUE THREAD

**Issue by StevenTCramer** [scriban/scriban#543]
```
public partial class {{ moxy.Class.DeclaringType.Name }}
{
  public partial class {{ moxy.Class.Name }}
  {
    public const string RouteTemplate = "{{ RouteTemplate }}";
    public HttpVerb GetHttpVerb() => {{ HttpVerb }};
    public string GetRoute({{ $getRouteSignatureSource }}) => FormattableString.Invariant($"{{$getRouteFormat}}");
    {{~ if $parametersSource ~}}
    {{ $parametersSource ~}}
    {{~ end ~}}
  }
}
```

I can't seem to get this to align correctly when I parametersSource is empty.

When populated 

![image](https://github.com/scriban/scriban/assets/357219/6cb79c4b-7290-4318-8010-414ac4a8e77c)

When Empty

![image](https://github.com/scriban/scriban/assets/357219/300c580d-5889-419a-afcc-855309664640)

I gave up and made this issue :) 

Thanks for the library its great with Moxy.

**Comment by xoofx** [comment]
An [empty string returns true](https://github.com/scriban/scriban/blob/master/doc/language.md#truthy-and-falsy) so it would be like you were not having a if at all, hence the tab.

So replace the `if` condition with something like `{{~ if $parametersSource == "" ~}}` or `{{~ if $parametersSource | string.empty ~}}` or `{{~ if $parametersSource | string.whitespace ~}}`

**Comment by StevenTCramer** [comment]
Works perfect.  Thanks much.  Great library.
