### ISSUE TITLE
Invalid token found "@"

### ISSUE THREAD

**Issue by malmaboy** [scriban/scriban#549]
Hi, 
I tried to execute this scriban code `{{ [" a", " 5", "6 "] | array.each @string.strip`, but it return this error: 
Invalid token found `@`. Expecting <EOL>/end of line.
This is the expected behavior ? Or there is any work around for this ? 
Thanks!

**Comment by xoofx** [comment]
That should work. Could you post a (non)functional small `Program.cs` here to see exactly what you are doing?

**Comment by malmaboy** [comment]
Hi, I explain myself wrongly.
I mean I try to use Liquid mode, more specifically when using LiquidTemplateContext.

**Comment by xoofx** [comment]
> I mean I try to use Liquid mode, more specifically when using LiquidTemplateContext.

Oh I see, afair, Liquid implementation in Scriban does not support this feature (it is a not part of Liquid originally), so this is a feature of the Scriban language only. The Liquid support was meant to be an intermediate solution while folks migrate to Scriban. I would not recommend using Liquid in Scriban.
