### ISSUE TITLE
Support for async function imports

### ISSUE THREAD

**Issue by juhani-honkala** [scriban/scriban#551]
Modern C# has lots of async functions. It would be great if Scriban had a native support for calling user defined async functions from the script.

**Comment by xoofx** [comment]
Async functions are supported. See for example the code in the tests [here](https://github.com/scriban/scriban/blob/38df14946721238d2f4badc7c0b6e8a1c594e23c/src/Scriban.Tests/TestAsync.cs#L15-L40)

**Comment by juhani-honkala** [comment]
Thanks a lot for help!

**Comment by juhani-honkala** [comment]
https://github.com/scriban/scriban/blob/38df14946721238d2f4badc7c0b6e8a1c594e23c/src/Scriban.Tests/TestAsync.cs#L15-L40
