### ISSUE TITLE
Simpliest possible use doesn't work for me and it's probably because I'm dumb

### ISSUE THREAD

**Issue by ShadyMedic** [scriban/scriban#565]
I know I'm going to facepalm really hard once somebody finds the problem here, but I've been trying to move with this for the past hour with no success.

My code:
```C#
public void GenerateTitle(int academicYearNumber)
{
    string templateText = LoadFileContent("Title.sbn"); //Works, see debug
    var template = Template.Parse(templateText);
    string academicYearTxt = academicYearNumber.ToString() + "/" + (academicYearNumber + 1).ToString(); //Works, see debug
    
    OutputHelper.PrintLine(academicYearTxt, ConsoleColor.DarkYellow); //Debug output
    OutputHelper.PrintLine(templateText, ConsoleColor.DarkYellow);    //Debug output
    
    outputFile.Write(template.Render(new { academicYear = academicYearTxt })); //Output works, see resulting file
}
```

Debug outputs:
```
2023/2024
    <h1>Souhrnná zpráva studentské ankety pro školní rok {{ academicYear }}</h1>
    <hr class="whitespace" />
```

Resulting file:
```html
    <h1>Souhrnná zpráva studentské ankety pro školní rok </h1>
    <hr class="whitespace" />
```

**The variable is simply missing**. I have no idea why. I tried changing case, I tried removing whitespace, always the same result.

What am I missing?

Thanks in advance.

**Comment by xoofx** [comment]
From the readme:

> **NOTICE**
>
> By default, Properties and methods of .NET objects are automatically exposed with lowercase and `_` names. It means that a property like `MyMethodIsNice` will be exposed as `my_method_is_nice`. This is the default convention, originally to match the behavior of liquid templates.
> If you want to change this behavior, you need to use a [`MemberRenamer`](https://github.com/scriban/scriban/blob/master/doc/runtime.md#member-renamer) delegate

So you should most likely use `{{ academic_year }}` in your template.

**Comment by ShadyMedic** [comment]
Awesome, works. Thank you for your swift reply and this library. 🧡
