### ISSUE TITLE
Random string to object conversion breaks my app

### ISSUE THREAD

**Issue by ShadyMedic** [scriban/scriban#569]
Hello, I think I'm missing something.

My template looks like this:
```
{{ for department in departments }}
  {{ for question in department.responses.Keys }}
    {{ question.GetContent() }}
  {{ end }}
{{ end }}
```
(I stripped a lot of unnecessary HTML for the sake of shortening this post.)

This is the code I use to render the template:
```cs
/* Department[] departmentsList = LIST OF Department OBJECTS */
string output = template.Render(new { departments = departmentsList });
```
The Department class defines the following attribute:
```cs
public Dictionary<Question, List<Response>> responses = new Dictionary<Question, List<Response>>();
```
And the Question class looks like this:
```cs
public class Question
{
    internal readonly string content;
    
    /* constructor is here */
    
    public string GetContent()
    {
        return content;
    }
}
```
When I run this code, the following error occurs on the line calling Render:
```
Scriban.Syntax.ScriptRuntimeException: (1,1) : error : Unable to convert type `string` to `Question`
```
However, when I change the rendering code like this:
```cs
/* Department[] departmentsList = LIST OF Department OBJECTS */
var questionList = departmentsList[0].responses.Keys; //All the departments have the same questions, so we can do this, though it's ugly
outputFile.Write(template.Render(new { departments = departmentsList, questions = questionList }));
```
And modify the template to use the questions variable:
```
{{ for department in departments }}
  {{ for question in questions }}
    {{ question.GetContent() }}
  {{ end }}
{{ end }}
```
I get a different error, which I suppose is a progress:
```
Scriban.Syntax.ScriptRuntimeException: <input>(25,53) : error : The function `question.GetContent` was not found
```
I'd like to pass the question list as a attribute (well, attribute of an attribute) of the Department instances and not as a separate variable.

What am I getting wrong? What causes the "Unable to convert type `string` to `Question`" error (what string is it talking about and why does it report line 1, column 1 as the location, when there's just some HTML in the original template at that position)? And how can I deal with the second error (which I suppose will still be occurring when I resolve the first one)?

Thanks in advance for any help.

**Comment by xoofx** [comment]
For both issues, it is likely, as stated in the readme:

> **NOTICE**
>
> By default, Properties and methods of .NET objects are automatically exposed with lowercase and `_` names. It means that a property like `MyMethodIsNice` will be exposed as `my_method_is_nice`. This is the default convention, originally to match the behavior of liquid templates.
> If you want to change this behavior, you need to use a [`MemberRenamer`](https://github.com/scriban/scriban/blob/master/doc/runtime.md#member-renamer) delegate

For the second issue, Scriban does not support by default instance method (for security reasons)

**Comment by ShadyMedic** [comment]
Forgot to answer this, but better late then never. Thank you for your swift reply, the links helped. Closing this now.
