### ISSUE TITLE
Regarding performance and caching

### ISSUE THREAD

**Issue by loonwong** [scriban/scriban#571]
Hello!

Our application renders the same Scriban template using different template contexts in parallel (in multiple threads). For performance reasons, could you confirm the following definitions:

1. `Template` can be safely reused in any thread and it is thread-safe.
2. To properly cache the `TemplateContext` object, I should use the object pool pattern and call `TemplateContext -> Reset()` before reuse.
3. To quickly create a `ScriptObject` object, I can use cloning of some default instance.

Can I somehow clone the `TemplateContext` instance (similar to a `ScriptObject`) to avoid using a pool?

Thank you.

**Comment by xoofx** [comment]
- For 1. and 2., yes.
- For 3. ScriptObjects might be pooled as well (and call `Clear`). They are just dictionaries. You can also initialize their capacity. 

> Can I somehow clone the TemplateContext instance (similar to a ScriptObject) to avoid using a pool?

In general, cloning is as costly as creating a new instance from scratch. You are better reusing a TemplateContext instance per thread with `Reset`.

**Comment by loonwong** [comment]
I meant cloning an already prepared template context (after rendering) with information about reflection. It should be faster than collecting MemberInfo's again or am I worng, maybe it's cached?

**Comment by xoofx** [comment]
> I meant cloning an already prepared template context (after rendering) with information about reflection. It should be faster than collecting MemberInfo's again or am I worng, maybe it's cached?

Reset does not clear the cache for member accessors (used [here](https://github.com/scriban/scriban/blob/42ad256ad1686d23fe72af6b88d68fe1e2cc6543/src/Scriban/TemplateContext.cs#L851-L865))

**Comment by loonwong** [comment]
Ok, thanks for your help and prompt response.
