### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by BenJBailey** [scriban/scriban#573]
@xoofx, Thank you for your hard work on this product. I realize you are extremely busy.

![thank you](https://media.tenor.com/images/8dd52c23e8e8ae2c49d0e5b973a73079/tenor.gif)

I was wondering if you had a plan to release scriban with the latest changes in master? Right now our product is using a fork but we would prefer to use the nuget version.

**Comment by xoofx** [comment]
Good call, forgot about the updates during the summer, just pushed `5.11.0`
