### ISSUE TITLE
Unable to use scriban in a .net 9 application

### ISSUE THREAD

**Issue by malain** [scriban/scriban#580]
When i try to add scriban to a .net 9 (or 8) application ('dotnet add package Scriban --version 5.12.0'),  i have the following error:

error: NU1101: Unable to find package Scriban. No packages exist with this id in source(s): dotnet-eng, dotnet-libraries, dotnet-public, dotnet-tools, dotnet6-transport, dotnet7, dotnet7-transport, dotnet8, dotnet8-transport, dotnet9, dotnet9-transport, vs-impl
error: Package 'Scriban' is incompatible with 'all' frameworks in project 'xxx.csproj'.

Will this frameworks be supported soon ?

**Comment by xoofx** [comment]
It is supported and it works (just tested), but it is most likely a problem on your side with your setup (temporary error? Can happen with NuGet). The package is on NuGet, so the "Unable to find package" is quite suspicious. Are you on Linux? 

Closing as unlikely a problem with Scriban.
