### ISSUE TITLE
Implement a way to disable SafeRuntime options

### ISSUE THREAD

**Issue by Tyrrrz** [scriban/scriban#61]
It would be nice if you could completely disable some of the saferuntime checks, e.g. `LoopLimit`. I'm working with huge amount of data and am generating large files using my templates. The loops in them can potentially iterate beyond `int.MaxValue`.

**Comment by xoofx** [comment]
Agree. PR welcome.

**Comment by binarycow** [comment]
@xoofx - [PR submitted](https://github.com/scriban/scriban/pull/348)

**Comment by Tyrrrz** [comment]
Closing as it was fixed by @binarycow
