### ISSUE TITLE
JObject as JSON

### ISSUE THREAD

**Issue by dazinator** [scriban/scriban#85]
Hello,

I have a question on how I might achieve the following.
On the .NET side, I have a model which has a property of type `JObject` (newtonsoft).
When you `ToString()` a `JObject` on the .NET side, it gives you JSON.

In the template, I'd like to render this property value as JSON.

Here is my template:

```
{{ for plugin in plugins }}
		var config{{ for.index }} = {{plugin.plugin_configuration}}		
{{ end }}
```

So above, the property `PluginConfiguration` is the `JObject`.

Here is the rendered output that I get:

```
var config0 = [[True], [1], [[foo, bar]]]
```

On the .NET side, if I do a `ToString()` I get the properly formatted JSON that I expect (and am trying to render in the template)

```
{
  "Start": true,
  "Times": 1,
  "Things": [
    "foo",
    "bar"
  ]
}

```

I tried changing my template to do:

```
var config{{ for.index }} = {{plugin.plugin_configuration.to_string()}}		

```

but it didn't like that..

I am not sure how scriban formats objects that it binds to when they are non primitive, is there a way to tell it to just do a `ToString()` ?

I am thinking of creating an additional public property that just does the ToString(), however I thought I'd raise this in case there was a better way I should be using scriban without making changes to my model to facilitate this.

**Comment by xoofx** [comment]
In the code today, we have an heuristic to first check IEnumerable before using the method ToString on the final object, and JObject are likely implementing IEnumerable...
So apart transforming a JObject into a scriban ScriptObject on your side (at C# level before feeding scriban), I'm afraid there is no easy workaround
